/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.com.ecopharma.emp.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the EmpActionHistory service. Represents a row in the &quot;eco_em_portlet_EmpActionHistory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.com.ecopharma.emp.model.impl.EmpActionHistoryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.com.ecopharma.emp.model.impl.EmpActionHistoryImpl}.
 * </p>
 *
 * @author tvt
 * @see EmpActionHistory
 * @see vn.com.ecopharma.emp.model.impl.EmpActionHistoryImpl
 * @see vn.com.ecopharma.emp.model.impl.EmpActionHistoryModelImpl
 * @generated
 */
public interface EmpActionHistoryModel extends BaseModel<EmpActionHistory>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a emp action history model instance should use the {@link EmpActionHistory} interface instead.
	 */

	/**
	 * Returns the primary key of this emp action history.
	 *
	 * @return the primary key of this emp action history
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this emp action history.
	 *
	 * @param primaryKey the primary key of this emp action history
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the emp action history ID of this emp action history.
	 *
	 * @return the emp action history ID of this emp action history
	 */
	public long getEmpActionHistoryId();

	/**
	 * Sets the emp action history ID of this emp action history.
	 *
	 * @param empActionHistoryId the emp action history ID of this emp action history
	 */
	public void setEmpActionHistoryId(long empActionHistoryId);

	/**
	 * Returns the emp ID of this emp action history.
	 *
	 * @return the emp ID of this emp action history
	 */
	public long getEmpId();

	/**
	 * Sets the emp ID of this emp action history.
	 *
	 * @param empId the emp ID of this emp action history
	 */
	public void setEmpId(long empId);

	/**
	 * Returns the action of this emp action history.
	 *
	 * @return the action of this emp action history
	 */
	@AutoEscape
	public String getAction();

	/**
	 * Sets the action of this emp action history.
	 *
	 * @param action the action of this emp action history
	 */
	public void setAction(String action);

	/**
	 * Returns the performed by of this emp action history.
	 *
	 * @return the performed by of this emp action history
	 */
	public long getPerformedBy();

	/**
	 * Sets the performed by of this emp action history.
	 *
	 * @param performedBy the performed by of this emp action history
	 */
	public void setPerformedBy(long performedBy);

	/**
	 * Returns the description of this emp action history.
	 *
	 * @return the description of this emp action history
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this emp action history.
	 *
	 * @param description the description of this emp action history
	 */
	public void setDescription(String description);

	/**
	 * Returns the status of this emp action history.
	 *
	 * @return the status of this emp action history
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this emp action history.
	 *
	 * @param status the status of this emp action history
	 */
	public void setStatus(String status);

	/**
	 * Returns the ref ID of this emp action history.
	 *
	 * @return the ref ID of this emp action history
	 */
	public long getRefId();

	/**
	 * Sets the ref ID of this emp action history.
	 *
	 * @param refId the ref ID of this emp action history
	 */
	public void setRefId(long refId);

	/**
	 * Returns the group ID of this emp action history.
	 *
	 * @return the group ID of this emp action history
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this emp action history.
	 *
	 * @param groupId the group ID of this emp action history
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this emp action history.
	 *
	 * @return the company ID of this emp action history
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this emp action history.
	 *
	 * @param companyId the company ID of this emp action history
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this emp action history.
	 *
	 * @return the user ID of this emp action history
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this emp action history.
	 *
	 * @param userId the user ID of this emp action history
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this emp action history.
	 *
	 * @return the user uuid of this emp action history
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this emp action history.
	 *
	 * @param userUuid the user uuid of this emp action history
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this emp action history.
	 *
	 * @return the user name of this emp action history
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this emp action history.
	 *
	 * @param userName the user name of this emp action history
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this emp action history.
	 *
	 * @return the create date of this emp action history
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this emp action history.
	 *
	 * @param createDate the create date of this emp action history
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this emp action history.
	 *
	 * @return the modified date of this emp action history
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this emp action history.
	 *
	 * @param modifiedDate the modified date of this emp action history
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(EmpActionHistory empActionHistory);

	@Override
	public int hashCode();

	@Override
	public CacheModel<EmpActionHistory> toCacheModel();

	@Override
	public EmpActionHistory toEscapedModel();

	@Override
	public EmpActionHistory toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}