/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.com.ecopharma.emp.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the EmpDiscipline service. Represents a row in the &quot;eco_em_portlet_EmpDiscipline&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.com.ecopharma.emp.model.impl.EmpDisciplineModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.com.ecopharma.emp.model.impl.EmpDisciplineImpl}.
 * </p>
 *
 * @author tvt
 * @see EmpDiscipline
 * @see vn.com.ecopharma.emp.model.impl.EmpDisciplineImpl
 * @see vn.com.ecopharma.emp.model.impl.EmpDisciplineModelImpl
 * @generated
 */
public interface EmpDisciplineModel extends BaseModel<EmpDiscipline>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a emp discipline model instance should use the {@link EmpDiscipline} interface instead.
	 */

	/**
	 * Returns the primary key of this emp discipline.
	 *
	 * @return the primary key of this emp discipline
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this emp discipline.
	 *
	 * @param primaryKey the primary key of this emp discipline
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the emp discipline ID of this emp discipline.
	 *
	 * @return the emp discipline ID of this emp discipline
	 */
	public long getEmpDisciplineId();

	/**
	 * Sets the emp discipline ID of this emp discipline.
	 *
	 * @param empDisciplineId the emp discipline ID of this emp discipline
	 */
	public void setEmpDisciplineId(long empDisciplineId);

	/**
	 * Returns the emp ID of this emp discipline.
	 *
	 * @return the emp ID of this emp discipline
	 */
	public long getEmpId();

	/**
	 * Sets the emp ID of this emp discipline.
	 *
	 * @param empId the emp ID of this emp discipline
	 */
	public void setEmpId(long empId);

	/**
	 * Returns the content of this emp discipline.
	 *
	 * @return the content of this emp discipline
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this emp discipline.
	 *
	 * @param content the content of this emp discipline
	 */
	public void setContent(String content);

	/**
	 * Returns the discipline type of this emp discipline.
	 *
	 * @return the discipline type of this emp discipline
	 */
	@AutoEscape
	public String getDisciplineType();

	/**
	 * Sets the discipline type of this emp discipline.
	 *
	 * @param disciplineType the discipline type of this emp discipline
	 */
	public void setDisciplineType(String disciplineType);

	/**
	 * Returns the effective date of this emp discipline.
	 *
	 * @return the effective date of this emp discipline
	 */
	public Date getEffectiveDate();

	/**
	 * Sets the effective date of this emp discipline.
	 *
	 * @param effectiveDate the effective date of this emp discipline
	 */
	public void setEffectiveDate(Date effectiveDate);

	/**
	 * Returns the additional discipline type of this emp discipline.
	 *
	 * @return the additional discipline type of this emp discipline
	 */
	@AutoEscape
	public String getAdditionalDisciplineType();

	/**
	 * Sets the additional discipline type of this emp discipline.
	 *
	 * @param additionalDisciplineType the additional discipline type of this emp discipline
	 */
	public void setAdditionalDisciplineType(String additionalDisciplineType);

	/**
	 * Returns the description of this emp discipline.
	 *
	 * @return the description of this emp discipline
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this emp discipline.
	 *
	 * @param description the description of this emp discipline
	 */
	public void setDescription(String description);

	/**
	 * Returns the group ID of this emp discipline.
	 *
	 * @return the group ID of this emp discipline
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this emp discipline.
	 *
	 * @param groupId the group ID of this emp discipline
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this emp discipline.
	 *
	 * @return the company ID of this emp discipline
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this emp discipline.
	 *
	 * @param companyId the company ID of this emp discipline
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this emp discipline.
	 *
	 * @return the user ID of this emp discipline
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this emp discipline.
	 *
	 * @param userId the user ID of this emp discipline
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this emp discipline.
	 *
	 * @return the user uuid of this emp discipline
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this emp discipline.
	 *
	 * @param userUuid the user uuid of this emp discipline
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this emp discipline.
	 *
	 * @return the user name of this emp discipline
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this emp discipline.
	 *
	 * @param userName the user name of this emp discipline
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this emp discipline.
	 *
	 * @return the create date of this emp discipline
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this emp discipline.
	 *
	 * @param createDate the create date of this emp discipline
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this emp discipline.
	 *
	 * @return the modified date of this emp discipline
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this emp discipline.
	 *
	 * @param modifiedDate the modified date of this emp discipline
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the deleted of this emp discipline.
	 *
	 * @return the deleted of this emp discipline
	 */
	public boolean getDeleted();

	/**
	 * Returns <code>true</code> if this emp discipline is deleted.
	 *
	 * @return <code>true</code> if this emp discipline is deleted; <code>false</code> otherwise
	 */
	public boolean isDeleted();

	/**
	 * Sets whether this emp discipline is deleted.
	 *
	 * @param deleted the deleted of this emp discipline
	 */
	public void setDeleted(boolean deleted);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(EmpDiscipline empDiscipline);

	@Override
	public int hashCode();

	@Override
	public CacheModel<EmpDiscipline> toCacheModel();

	@Override
	public EmpDiscipline toEscapedModel();

	@Override
	public EmpDiscipline toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}