/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.com.ecopharma.emp.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the EmpLaborContract service. Represents a row in the &quot;eco_em_portlet_EmpLaborContract&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.com.ecopharma.emp.model.impl.EmpLaborContractModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.com.ecopharma.emp.model.impl.EmpLaborContractImpl}.
 * </p>
 *
 * @author tvt
 * @see EmpLaborContract
 * @see vn.com.ecopharma.emp.model.impl.EmpLaborContractImpl
 * @see vn.com.ecopharma.emp.model.impl.EmpLaborContractModelImpl
 * @generated
 */
public interface EmpLaborContractModel extends BaseModel<EmpLaborContract>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a emp labor contract model instance should use the {@link EmpLaborContract} interface instead.
	 */

	/**
	 * Returns the primary key of this emp labor contract.
	 *
	 * @return the primary key of this emp labor contract
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this emp labor contract.
	 *
	 * @param primaryKey the primary key of this emp labor contract
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the emp labor contract ID of this emp labor contract.
	 *
	 * @return the emp labor contract ID of this emp labor contract
	 */
	public long getEmpLaborContractId();

	/**
	 * Sets the emp labor contract ID of this emp labor contract.
	 *
	 * @param empLaborContractId the emp labor contract ID of this emp labor contract
	 */
	public void setEmpLaborContractId(long empLaborContractId);

	/**
	 * Returns the emp ID of this emp labor contract.
	 *
	 * @return the emp ID of this emp labor contract
	 */
	public long getEmpId();

	/**
	 * Sets the emp ID of this emp labor contract.
	 *
	 * @param empId the emp ID of this emp labor contract
	 */
	public void setEmpId(long empId);

	/**
	 * Returns the labor contract signed date of this emp labor contract.
	 *
	 * @return the labor contract signed date of this emp labor contract
	 */
	public Date getLaborContractSignedDate();

	/**
	 * Sets the labor contract signed date of this emp labor contract.
	 *
	 * @param laborContractSignedDate the labor contract signed date of this emp labor contract
	 */
	public void setLaborContractSignedDate(Date laborContractSignedDate);

	/**
	 * Returns the labor contract expired date of this emp labor contract.
	 *
	 * @return the labor contract expired date of this emp labor contract
	 */
	public Date getLaborContractExpiredDate();

	/**
	 * Sets the labor contract expired date of this emp labor contract.
	 *
	 * @param laborContractExpiredDate the labor contract expired date of this emp labor contract
	 */
	public void setLaborContractExpiredDate(Date laborContractExpiredDate);

	/**
	 * Returns the labor contract signed type of this emp labor contract.
	 *
	 * @return the labor contract signed type of this emp labor contract
	 */
	@AutoEscape
	public String getLaborContractSignedType();

	/**
	 * Sets the labor contract signed type of this emp labor contract.
	 *
	 * @param laborContractSignedType the labor contract signed type of this emp labor contract
	 */
	public void setLaborContractSignedType(String laborContractSignedType);

	/**
	 * Returns the signed times of this emp labor contract.
	 *
	 * @return the signed times of this emp labor contract
	 */
	public int getSignedTimes();

	/**
	 * Sets the signed times of this emp labor contract.
	 *
	 * @param signedTimes the signed times of this emp labor contract
	 */
	public void setSignedTimes(int signedTimes);

	/**
	 * Returns the latest of this emp labor contract.
	 *
	 * @return the latest of this emp labor contract
	 */
	public boolean getLatest();

	/**
	 * Returns <code>true</code> if this emp labor contract is latest.
	 *
	 * @return <code>true</code> if this emp labor contract is latest; <code>false</code> otherwise
	 */
	public boolean isLatest();

	/**
	 * Sets whether this emp labor contract is latest.
	 *
	 * @param latest the latest of this emp labor contract
	 */
	public void setLatest(boolean latest);

	/**
	 * Returns the group ID of this emp labor contract.
	 *
	 * @return the group ID of this emp labor contract
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this emp labor contract.
	 *
	 * @param groupId the group ID of this emp labor contract
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this emp labor contract.
	 *
	 * @return the company ID of this emp labor contract
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this emp labor contract.
	 *
	 * @param companyId the company ID of this emp labor contract
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this emp labor contract.
	 *
	 * @return the user ID of this emp labor contract
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this emp labor contract.
	 *
	 * @param userId the user ID of this emp labor contract
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this emp labor contract.
	 *
	 * @return the user uuid of this emp labor contract
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this emp labor contract.
	 *
	 * @param userUuid the user uuid of this emp labor contract
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this emp labor contract.
	 *
	 * @return the user name of this emp labor contract
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this emp labor contract.
	 *
	 * @param userName the user name of this emp labor contract
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this emp labor contract.
	 *
	 * @return the create date of this emp labor contract
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this emp labor contract.
	 *
	 * @param createDate the create date of this emp labor contract
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this emp labor contract.
	 *
	 * @return the modified date of this emp labor contract
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this emp labor contract.
	 *
	 * @param modifiedDate the modified date of this emp labor contract
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(EmpLaborContract empLaborContract);

	@Override
	public int hashCode();

	@Override
	public CacheModel<EmpLaborContract> toCacheModel();

	@Override
	public EmpLaborContract toEscapedModel();

	@Override
	public EmpLaborContract toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}