/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.com.ecopharma.emp.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the EmpOrgRelationship service. Represents a row in the &quot;eco_em_portlet_EmpOrgRelationship&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.com.ecopharma.emp.model.impl.EmpOrgRelationshipModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.com.ecopharma.emp.model.impl.EmpOrgRelationshipImpl}.
 * </p>
 *
 * @author tvt
 * @see EmpOrgRelationship
 * @see vn.com.ecopharma.emp.model.impl.EmpOrgRelationshipImpl
 * @see vn.com.ecopharma.emp.model.impl.EmpOrgRelationshipModelImpl
 * @generated
 */
public interface EmpOrgRelationshipModel extends BaseModel<EmpOrgRelationship>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a emp org relationship model instance should use the {@link EmpOrgRelationship} interface instead.
	 */

	/**
	 * Returns the primary key of this emp org relationship.
	 *
	 * @return the primary key of this emp org relationship
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this emp org relationship.
	 *
	 * @param primaryKey the primary key of this emp org relationship
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the emp org relationship ID of this emp org relationship.
	 *
	 * @return the emp org relationship ID of this emp org relationship
	 */
	public long getEmpOrgRelationshipId();

	/**
	 * Sets the emp org relationship ID of this emp org relationship.
	 *
	 * @param empOrgRelationshipId the emp org relationship ID of this emp org relationship
	 */
	public void setEmpOrgRelationshipId(long empOrgRelationshipId);

	/**
	 * Returns the emp ID of this emp org relationship.
	 *
	 * @return the emp ID of this emp org relationship
	 */
	public long getEmpId();

	/**
	 * Sets the emp ID of this emp org relationship.
	 *
	 * @param empId the emp ID of this emp org relationship
	 */
	public void setEmpId(long empId);

	/**
	 * Returns the org class name of this emp org relationship.
	 *
	 * @return the org class name of this emp org relationship
	 */
	@AutoEscape
	public String getOrgClassName();

	/**
	 * Sets the org class name of this emp org relationship.
	 *
	 * @param orgClassName the org class name of this emp org relationship
	 */
	public void setOrgClassName(String orgClassName);

	/**
	 * Returns the org class p k of this emp org relationship.
	 *
	 * @return the org class p k of this emp org relationship
	 */
	public long getOrgClassPK();

	/**
	 * Sets the org class p k of this emp org relationship.
	 *
	 * @param orgClassPK the org class p k of this emp org relationship
	 */
	public void setOrgClassPK(long orgClassPK);

	/**
	 * Returns the head of org of this emp org relationship.
	 *
	 * @return the head of org of this emp org relationship
	 */
	public boolean getHeadOfOrg();

	/**
	 * Returns <code>true</code> if this emp org relationship is head of org.
	 *
	 * @return <code>true</code> if this emp org relationship is head of org; <code>false</code> otherwise
	 */
	public boolean isHeadOfOrg();

	/**
	 * Sets whether this emp org relationship is head of org.
	 *
	 * @param headOfOrg the head of org of this emp org relationship
	 */
	public void setHeadOfOrg(boolean headOfOrg);

	/**
	 * Returns the deputy of org of this emp org relationship.
	 *
	 * @return the deputy of org of this emp org relationship
	 */
	public boolean getDeputyOfOrg();

	/**
	 * Returns <code>true</code> if this emp org relationship is deputy of org.
	 *
	 * @return <code>true</code> if this emp org relationship is deputy of org; <code>false</code> otherwise
	 */
	public boolean isDeputyOfOrg();

	/**
	 * Sets whether this emp org relationship is deputy of org.
	 *
	 * @param deputyOfOrg the deputy of org of this emp org relationship
	 */
	public void setDeputyOfOrg(boolean deputyOfOrg);

	/**
	 * Returns the group ID of this emp org relationship.
	 *
	 * @return the group ID of this emp org relationship
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this emp org relationship.
	 *
	 * @param groupId the group ID of this emp org relationship
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this emp org relationship.
	 *
	 * @return the company ID of this emp org relationship
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this emp org relationship.
	 *
	 * @param companyId the company ID of this emp org relationship
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this emp org relationship.
	 *
	 * @return the user ID of this emp org relationship
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this emp org relationship.
	 *
	 * @param userId the user ID of this emp org relationship
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this emp org relationship.
	 *
	 * @return the user uuid of this emp org relationship
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this emp org relationship.
	 *
	 * @param userUuid the user uuid of this emp org relationship
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this emp org relationship.
	 *
	 * @return the user name of this emp org relationship
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this emp org relationship.
	 *
	 * @param userName the user name of this emp org relationship
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this emp org relationship.
	 *
	 * @return the create date of this emp org relationship
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this emp org relationship.
	 *
	 * @param createDate the create date of this emp org relationship
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this emp org relationship.
	 *
	 * @return the modified date of this emp org relationship
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this emp org relationship.
	 *
	 * @param modifiedDate the modified date of this emp org relationship
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(EmpOrgRelationship empOrgRelationship);

	@Override
	public int hashCode();

	@Override
	public CacheModel<EmpOrgRelationship> toCacheModel();

	@Override
	public EmpOrgRelationship toEscapedModel();

	@Override
	public EmpOrgRelationship toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}