/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.com.ecopharma.emp.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Specialized service. Represents a row in the &quot;eco_em_portlet_Specialized&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.com.ecopharma.emp.model.impl.SpecializedModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.com.ecopharma.emp.model.impl.SpecializedImpl}.
 * </p>
 *
 * @author tvt
 * @see Specialized
 * @see vn.com.ecopharma.emp.model.impl.SpecializedImpl
 * @see vn.com.ecopharma.emp.model.impl.SpecializedModelImpl
 * @generated
 */
public interface SpecializedModel extends BaseModel<Specialized>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a specialized model instance should use the {@link Specialized} interface instead.
	 */

	/**
	 * Returns the primary key of this specialized.
	 *
	 * @return the primary key of this specialized
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this specialized.
	 *
	 * @param primaryKey the primary key of this specialized
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the specialized ID of this specialized.
	 *
	 * @return the specialized ID of this specialized
	 */
	public long getSpecializedId();

	/**
	 * Sets the specialized ID of this specialized.
	 *
	 * @param specializedId the specialized ID of this specialized
	 */
	public void setSpecializedId(long specializedId);

	/**
	 * Returns the specialized code of this specialized.
	 *
	 * @return the specialized code of this specialized
	 */
	@AutoEscape
	public String getSpecializedCode();

	/**
	 * Sets the specialized code of this specialized.
	 *
	 * @param specializedCode the specialized code of this specialized
	 */
	public void setSpecializedCode(String specializedCode);

	/**
	 * Returns the name of this specialized.
	 *
	 * @return the name of this specialized
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this specialized.
	 *
	 * @param name the name of this specialized
	 */
	public void setName(String name);

	/**
	 * Returns the level of this specialized.
	 *
	 * @return the level of this specialized
	 */
	public int getLevel();

	/**
	 * Sets the level of this specialized.
	 *
	 * @param level the level of this specialized
	 */
	public void setLevel(int level);

	/**
	 * Returns the parent ID of this specialized.
	 *
	 * @return the parent ID of this specialized
	 */
	public long getParentId();

	/**
	 * Sets the parent ID of this specialized.
	 *
	 * @param parentId the parent ID of this specialized
	 */
	public void setParentId(long parentId);

	/**
	 * Returns the university of this specialized.
	 *
	 * @return the university of this specialized
	 */
	public boolean getUniversity();

	/**
	 * Returns <code>true</code> if this specialized is university.
	 *
	 * @return <code>true</code> if this specialized is university; <code>false</code> otherwise
	 */
	public boolean isUniversity();

	/**
	 * Sets whether this specialized is university.
	 *
	 * @param university the university of this specialized
	 */
	public void setUniversity(boolean university);

	/**
	 * Returns the college of this specialized.
	 *
	 * @return the college of this specialized
	 */
	public boolean getCollege();

	/**
	 * Returns <code>true</code> if this specialized is college.
	 *
	 * @return <code>true</code> if this specialized is college; <code>false</code> otherwise
	 */
	public boolean isCollege();

	/**
	 * Sets whether this specialized is college.
	 *
	 * @param college the college of this specialized
	 */
	public void setCollege(boolean college);

	/**
	 * Returns the vocational college of this specialized.
	 *
	 * @return the vocational college of this specialized
	 */
	public boolean getVocationalCollege();

	/**
	 * Returns <code>true</code> if this specialized is vocational college.
	 *
	 * @return <code>true</code> if this specialized is vocational college; <code>false</code> otherwise
	 */
	public boolean isVocationalCollege();

	/**
	 * Sets whether this specialized is vocational college.
	 *
	 * @param vocationalCollege the vocational college of this specialized
	 */
	public void setVocationalCollege(boolean vocationalCollege);

	/**
	 * Returns the vocational of this specialized.
	 *
	 * @return the vocational of this specialized
	 */
	public boolean getVocational();

	/**
	 * Returns <code>true</code> if this specialized is vocational.
	 *
	 * @return <code>true</code> if this specialized is vocational; <code>false</code> otherwise
	 */
	public boolean isVocational();

	/**
	 * Sets whether this specialized is vocational.
	 *
	 * @param vocational the vocational of this specialized
	 */
	public void setVocational(boolean vocational);

	/**
	 * Returns the group ID of this specialized.
	 *
	 * @return the group ID of this specialized
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this specialized.
	 *
	 * @param groupId the group ID of this specialized
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this specialized.
	 *
	 * @return the company ID of this specialized
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this specialized.
	 *
	 * @param companyId the company ID of this specialized
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this specialized.
	 *
	 * @return the user ID of this specialized
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this specialized.
	 *
	 * @param userId the user ID of this specialized
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this specialized.
	 *
	 * @return the user uuid of this specialized
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this specialized.
	 *
	 * @param userUuid the user uuid of this specialized
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this specialized.
	 *
	 * @return the user name of this specialized
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this specialized.
	 *
	 * @param userName the user name of this specialized
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this specialized.
	 *
	 * @return the create date of this specialized
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this specialized.
	 *
	 * @param createDate the create date of this specialized
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this specialized.
	 *
	 * @return the modified date of this specialized
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this specialized.
	 *
	 * @param modifiedDate the modified date of this specialized
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Specialized specialized);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Specialized> toCacheModel();

	@Override
	public Specialized toEscapedModel();

	@Override
	public Specialized toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}