/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.com.ecopharma.emp.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VacationLeave service. Represents a row in the &quot;eco_em_portlet_VacationLeave&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.com.ecopharma.emp.model.impl.VacationLeaveModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.com.ecopharma.emp.model.impl.VacationLeaveImpl}.
 * </p>
 *
 * @author tvt
 * @see VacationLeave
 * @see vn.com.ecopharma.emp.model.impl.VacationLeaveImpl
 * @see vn.com.ecopharma.emp.model.impl.VacationLeaveModelImpl
 * @generated
 */
public interface VacationLeaveModel extends BaseModel<VacationLeave>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vacation leave model instance should use the {@link VacationLeave} interface instead.
	 */

	/**
	 * Returns the primary key of this vacation leave.
	 *
	 * @return the primary key of this vacation leave
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this vacation leave.
	 *
	 * @param primaryKey the primary key of this vacation leave
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the vacation leave ID of this vacation leave.
	 *
	 * @return the vacation leave ID of this vacation leave
	 */
	public long getVacationLeaveId();

	/**
	 * Sets the vacation leave ID of this vacation leave.
	 *
	 * @param vacationLeaveId the vacation leave ID of this vacation leave
	 */
	public void setVacationLeaveId(long vacationLeaveId);

	/**
	 * Returns the emp ID of this vacation leave.
	 *
	 * @return the emp ID of this vacation leave
	 */
	public long getEmpId();

	/**
	 * Sets the emp ID of this vacation leave.
	 *
	 * @param empId the emp ID of this vacation leave
	 */
	public void setEmpId(long empId);

	/**
	 * Returns the leave type of this vacation leave.
	 *
	 * @return the leave type of this vacation leave
	 */
	@AutoEscape
	public String getLeaveType();

	/**
	 * Sets the leave type of this vacation leave.
	 *
	 * @param leaveType the leave type of this vacation leave
	 */
	public void setLeaveType(String leaveType);

	/**
	 * Returns the leave from of this vacation leave.
	 *
	 * @return the leave from of this vacation leave
	 */
	public Date getLeaveFrom();

	/**
	 * Sets the leave from of this vacation leave.
	 *
	 * @param leaveFrom the leave from of this vacation leave
	 */
	public void setLeaveFrom(Date leaveFrom);

	/**
	 * Returns the leave to of this vacation leave.
	 *
	 * @return the leave to of this vacation leave
	 */
	public Date getLeaveTo();

	/**
	 * Sets the leave to of this vacation leave.
	 *
	 * @param leaveTo the leave to of this vacation leave
	 */
	public void setLeaveTo(Date leaveTo);

	/**
	 * Returns the actual to of this vacation leave.
	 *
	 * @return the actual to of this vacation leave
	 */
	public Date getActualTo();

	/**
	 * Sets the actual to of this vacation leave.
	 *
	 * @param actualTo the actual to of this vacation leave
	 */
	public void setActualTo(Date actualTo);

	/**
	 * Returns the reason of this vacation leave.
	 *
	 * @return the reason of this vacation leave
	 */
	@AutoEscape
	public String getReason();

	/**
	 * Sets the reason of this vacation leave.
	 *
	 * @param reason the reason of this vacation leave
	 */
	public void setReason(String reason);

	/**
	 * Returns the description of this vacation leave.
	 *
	 * @return the description of this vacation leave
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this vacation leave.
	 *
	 * @param description the description of this vacation leave
	 */
	public void setDescription(String description);

	/**
	 * Returns the group ID of this vacation leave.
	 *
	 * @return the group ID of this vacation leave
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this vacation leave.
	 *
	 * @param groupId the group ID of this vacation leave
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this vacation leave.
	 *
	 * @return the company ID of this vacation leave
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this vacation leave.
	 *
	 * @param companyId the company ID of this vacation leave
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this vacation leave.
	 *
	 * @return the user ID of this vacation leave
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this vacation leave.
	 *
	 * @param userId the user ID of this vacation leave
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this vacation leave.
	 *
	 * @return the user uuid of this vacation leave
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this vacation leave.
	 *
	 * @param userUuid the user uuid of this vacation leave
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this vacation leave.
	 *
	 * @return the user name of this vacation leave
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this vacation leave.
	 *
	 * @param userName the user name of this vacation leave
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this vacation leave.
	 *
	 * @return the create date of this vacation leave
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this vacation leave.
	 *
	 * @param createDate the create date of this vacation leave
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this vacation leave.
	 *
	 * @return the modified date of this vacation leave
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this vacation leave.
	 *
	 * @param modifiedDate the modified date of this vacation leave
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(VacationLeave vacationLeave);

	@Override
	public int hashCode();

	@Override
	public CacheModel<VacationLeave> toCacheModel();

	@Override
	public VacationLeave toEscapedModel();

	@Override
	public VacationLeave toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}