/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.com.ecopharma.hrm.tt.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TimeTracking service. Represents a row in the &quot;eco_ttp_TimeTracking&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.com.ecopharma.hrm.tt.model.impl.TimeTrackingModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.com.ecopharma.hrm.tt.model.impl.TimeTrackingImpl}.
 * </p>
 *
 * @author tvt
 * @see TimeTracking
 * @see vn.com.ecopharma.hrm.tt.model.impl.TimeTrackingImpl
 * @see vn.com.ecopharma.hrm.tt.model.impl.TimeTrackingModelImpl
 * @generated
 */
public interface TimeTrackingModel extends BaseModel<TimeTracking>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a time tracking model instance should use the {@link TimeTracking} interface instead.
	 */

	/**
	 * Returns the primary key of this time tracking.
	 *
	 * @return the primary key of this time tracking
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this time tracking.
	 *
	 * @param primaryKey the primary key of this time tracking
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the time tracking ID of this time tracking.
	 *
	 * @return the time tracking ID of this time tracking
	 */
	public long getTimeTrackingId();

	/**
	 * Sets the time tracking ID of this time tracking.
	 *
	 * @param timeTrackingId the time tracking ID of this time tracking
	 */
	public void setTimeTrackingId(long timeTrackingId);

	/**
	 * Returns the emp ID of this time tracking.
	 *
	 * @return the emp ID of this time tracking
	 */
	public long getEmpId();

	/**
	 * Sets the emp ID of this time tracking.
	 *
	 * @param empId the emp ID of this time tracking
	 */
	public void setEmpId(long empId);

	/**
	 * Returns the date of this time tracking.
	 *
	 * @return the date of this time tracking
	 */
	public Date getDate();

	/**
	 * Sets the date of this time tracking.
	 *
	 * @param date the date of this time tracking
	 */
	public void setDate(Date date);

	/**
	 * Returns the in1 of this time tracking.
	 *
	 * @return the in1 of this time tracking
	 */
	public Date getIn1();

	/**
	 * Sets the in1 of this time tracking.
	 *
	 * @param in1 the in1 of this time tracking
	 */
	public void setIn1(Date in1);

	/**
	 * Returns the out1 of this time tracking.
	 *
	 * @return the out1 of this time tracking
	 */
	public Date getOut1();

	/**
	 * Sets the out1 of this time tracking.
	 *
	 * @param out1 the out1 of this time tracking
	 */
	public void setOut1(Date out1);

	/**
	 * Returns the in2 of this time tracking.
	 *
	 * @return the in2 of this time tracking
	 */
	public Date getIn2();

	/**
	 * Sets the in2 of this time tracking.
	 *
	 * @param in2 the in2 of this time tracking
	 */
	public void setIn2(Date in2);

	/**
	 * Returns the out2 of this time tracking.
	 *
	 * @return the out2 of this time tracking
	 */
	public Date getOut2();

	/**
	 * Sets the out2 of this time tracking.
	 *
	 * @param out2 the out2 of this time tracking
	 */
	public void setOut2(Date out2);

	/**
	 * Returns the in3 of this time tracking.
	 *
	 * @return the in3 of this time tracking
	 */
	public Date getIn3();

	/**
	 * Sets the in3 of this time tracking.
	 *
	 * @param in3 the in3 of this time tracking
	 */
	public void setIn3(Date in3);

	/**
	 * Returns the out3 of this time tracking.
	 *
	 * @return the out3 of this time tracking
	 */
	public Date getOut3();

	/**
	 * Sets the out3 of this time tracking.
	 *
	 * @param out3 the out3 of this time tracking
	 */
	public void setOut3(Date out3);

	/**
	 * Returns the group ID of this time tracking.
	 *
	 * @return the group ID of this time tracking
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this time tracking.
	 *
	 * @param groupId the group ID of this time tracking
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this time tracking.
	 *
	 * @return the company ID of this time tracking
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this time tracking.
	 *
	 * @param companyId the company ID of this time tracking
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this time tracking.
	 *
	 * @return the user ID of this time tracking
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this time tracking.
	 *
	 * @param userId the user ID of this time tracking
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this time tracking.
	 *
	 * @return the user uuid of this time tracking
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this time tracking.
	 *
	 * @param userUuid the user uuid of this time tracking
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this time tracking.
	 *
	 * @return the user name of this time tracking
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this time tracking.
	 *
	 * @param userName the user name of this time tracking
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this time tracking.
	 *
	 * @return the create date of this time tracking
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this time tracking.
	 *
	 * @param createDate the create date of this time tracking
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this time tracking.
	 *
	 * @return the modified date of this time tracking
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this time tracking.
	 *
	 * @param modifiedDate the modified date of this time tracking
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the leave ref ID of this time tracking.
	 *
	 * @return the leave ref ID of this time tracking
	 */
	public long getLeaveRefId();

	/**
	 * Sets the leave ref ID of this time tracking.
	 *
	 * @param leaveRefId the leave ref ID of this time tracking
	 */
	public void setLeaveRefId(long leaveRefId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(TimeTracking timeTracking);

	@Override
	public int hashCode();

	@Override
	public CacheModel<TimeTracking> toCacheModel();

	@Override
	public TimeTracking toEscapedModel();

	@Override
	public TimeTracking toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}