/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.com.ecopharma.emp.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import vn.com.ecopharma.emp.model.District;
import vn.com.ecopharma.emp.model.DistrictModel;
import vn.com.ecopharma.emp.model.DistrictSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the District service. Represents a row in the &quot;eco_em_portlet_District&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.com.ecopharma.emp.model.DistrictModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DistrictImpl}.
 * </p>
 *
 * @author tvt
 * @see DistrictImpl
 * @see vn.com.ecopharma.emp.model.District
 * @see vn.com.ecopharma.emp.model.DistrictModel
 * @generated
 */
@JSON(strict = true)
public class DistrictModelImpl extends BaseModelImpl<District>
	implements DistrictModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a district model instance should use the {@link vn.com.ecopharma.emp.model.District} interface instead.
	 */
	public static final String TABLE_NAME = "eco_em_portlet_District";
	public static final Object[][] TABLE_COLUMNS = {
			{ "districtId", Types.BIGINT },
			{ "regionCode", Types.VARCHAR },
			{ "districtType", Types.VARCHAR },
			{ "name", Types.VARCHAR },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table eco_em_portlet_District (districtId LONG not null primary key,regionCode VARCHAR(75) null,districtType VARCHAR(75) null,name VARCHAR(75) null,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table eco_em_portlet_District";
	public static final String ORDER_BY_JPQL = " ORDER BY district.districtId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY eco_em_portlet_District.districtId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.com.ecopharma.emp.model.District"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.com.ecopharma.emp.model.District"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.vn.com.ecopharma.emp.model.District"),
			true);
	public static long NAME_COLUMN_BITMASK = 1L;
	public static long REGIONCODE_COLUMN_BITMASK = 2L;
	public static long DISTRICTID_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static District toModel(DistrictSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		District model = new DistrictImpl();

		model.setDistrictId(soapModel.getDistrictId());
		model.setRegionCode(soapModel.getRegionCode());
		model.setDistrictType(soapModel.getDistrictType());
		model.setName(soapModel.getName());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<District> toModels(DistrictSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<District> models = new ArrayList<District>(soapModels.length);

		for (DistrictSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.com.ecopharma.emp.model.District"));

	public DistrictModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _districtId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setDistrictId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _districtId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return District.class;
	}

	@Override
	public String getModelClassName() {
		return District.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("districtId", getDistrictId());
		attributes.put("regionCode", getRegionCode());
		attributes.put("districtType", getDistrictType());
		attributes.put("name", getName());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long districtId = (Long)attributes.get("districtId");

		if (districtId != null) {
			setDistrictId(districtId);
		}

		String regionCode = (String)attributes.get("regionCode");

		if (regionCode != null) {
			setRegionCode(regionCode);
		}

		String districtType = (String)attributes.get("districtType");

		if (districtType != null) {
			setDistrictType(districtType);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}
	}

	@JSON
	@Override
	public long getDistrictId() {
		return _districtId;
	}

	@Override
	public void setDistrictId(long districtId) {
		_districtId = districtId;
	}

	@JSON
	@Override
	public String getRegionCode() {
		if (_regionCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _regionCode;
		}
	}

	@Override
	public void setRegionCode(String regionCode) {
		_columnBitmask |= REGIONCODE_COLUMN_BITMASK;

		if (_originalRegionCode == null) {
			_originalRegionCode = _regionCode;
		}

		_regionCode = regionCode;
	}

	public String getOriginalRegionCode() {
		return GetterUtil.getString(_originalRegionCode);
	}

	@JSON
	@Override
	public String getDistrictType() {
		if (_districtType == null) {
			return StringPool.BLANK;
		}
		else {
			return _districtType;
		}
	}

	@Override
	public void setDistrictType(String districtType) {
		_districtType = districtType;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_columnBitmask |= NAME_COLUMN_BITMASK;

		if (_originalName == null) {
			_originalName = _name;
		}

		_name = name;
	}

	public String getOriginalName() {
		return GetterUtil.getString(_originalName);
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			District.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public District toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (District)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DistrictImpl districtImpl = new DistrictImpl();

		districtImpl.setDistrictId(getDistrictId());
		districtImpl.setRegionCode(getRegionCode());
		districtImpl.setDistrictType(getDistrictType());
		districtImpl.setName(getName());
		districtImpl.setGroupId(getGroupId());
		districtImpl.setCompanyId(getCompanyId());
		districtImpl.setUserId(getUserId());
		districtImpl.setUserName(getUserName());
		districtImpl.setCreateDate(getCreateDate());
		districtImpl.setModifiedDate(getModifiedDate());

		districtImpl.resetOriginalValues();

		return districtImpl;
	}

	@Override
	public int compareTo(District district) {
		long primaryKey = district.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof District)) {
			return false;
		}

		District district = (District)obj;

		long primaryKey = district.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		DistrictModelImpl districtModelImpl = this;

		districtModelImpl._originalRegionCode = districtModelImpl._regionCode;

		districtModelImpl._originalName = districtModelImpl._name;

		districtModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<District> toCacheModel() {
		DistrictCacheModel districtCacheModel = new DistrictCacheModel();

		districtCacheModel.districtId = getDistrictId();

		districtCacheModel.regionCode = getRegionCode();

		String regionCode = districtCacheModel.regionCode;

		if ((regionCode != null) && (regionCode.length() == 0)) {
			districtCacheModel.regionCode = null;
		}

		districtCacheModel.districtType = getDistrictType();

		String districtType = districtCacheModel.districtType;

		if ((districtType != null) && (districtType.length() == 0)) {
			districtCacheModel.districtType = null;
		}

		districtCacheModel.name = getName();

		String name = districtCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			districtCacheModel.name = null;
		}

		districtCacheModel.groupId = getGroupId();

		districtCacheModel.companyId = getCompanyId();

		districtCacheModel.userId = getUserId();

		districtCacheModel.userName = getUserName();

		String userName = districtCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			districtCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			districtCacheModel.createDate = createDate.getTime();
		}
		else {
			districtCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			districtCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			districtCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return districtCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(21);

		sb.append("{districtId=");
		sb.append(getDistrictId());
		sb.append(", regionCode=");
		sb.append(getRegionCode());
		sb.append(", districtType=");
		sb.append(getDistrictType());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(34);

		sb.append("<model><model-name>");
		sb.append("vn.com.ecopharma.emp.model.District");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>districtId</column-name><column-value><![CDATA[");
		sb.append(getDistrictId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>regionCode</column-name><column-value><![CDATA[");
		sb.append(getRegionCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>districtType</column-name><column-value><![CDATA[");
		sb.append(getDistrictType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = District.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			District.class
		};
	private long _districtId;
	private String _regionCode;
	private String _originalRegionCode;
	private String _districtType;
	private String _name;
	private String _originalName;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private long _columnBitmask;
	private District _escapedModel;
}