/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.com.ecopharma.emp.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import vn.com.ecopharma.emp.model.EmpAnualLeave;
import vn.com.ecopharma.emp.model.EmpAnualLeaveModel;
import vn.com.ecopharma.emp.model.EmpAnualLeaveSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the EmpAnualLeave service. Represents a row in the &quot;eco_em_portlet_EmpAnualLeave&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.com.ecopharma.emp.model.EmpAnualLeaveModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EmpAnualLeaveImpl}.
 * </p>
 *
 * @author tvt
 * @see EmpAnualLeaveImpl
 * @see vn.com.ecopharma.emp.model.EmpAnualLeave
 * @see vn.com.ecopharma.emp.model.EmpAnualLeaveModel
 * @generated
 */
@JSON(strict = true)
public class EmpAnualLeaveModelImpl extends BaseModelImpl<EmpAnualLeave>
	implements EmpAnualLeaveModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a emp anual leave model instance should use the {@link vn.com.ecopharma.emp.model.EmpAnualLeave} interface instead.
	 */
	public static final String TABLE_NAME = "eco_em_portlet_EmpAnualLeave";
	public static final Object[][] TABLE_COLUMNS = {
			{ "empAnualLeaveId", Types.BIGINT },
			{ "empId", Types.BIGINT },
			{ "noOfAnualLeave", Types.DOUBLE },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table eco_em_portlet_EmpAnualLeave (empAnualLeaveId LONG not null primary key,empId LONG,noOfAnualLeave DOUBLE,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table eco_em_portlet_EmpAnualLeave";
	public static final String ORDER_BY_JPQL = " ORDER BY empAnualLeave.empAnualLeaveId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY eco_em_portlet_EmpAnualLeave.empAnualLeaveId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.com.ecopharma.emp.model.EmpAnualLeave"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.com.ecopharma.emp.model.EmpAnualLeave"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static EmpAnualLeave toModel(EmpAnualLeaveSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		EmpAnualLeave model = new EmpAnualLeaveImpl();

		model.setEmpAnualLeaveId(soapModel.getEmpAnualLeaveId());
		model.setEmpId(soapModel.getEmpId());
		model.setNoOfAnualLeave(soapModel.getNoOfAnualLeave());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<EmpAnualLeave> toModels(EmpAnualLeaveSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<EmpAnualLeave> models = new ArrayList<EmpAnualLeave>(soapModels.length);

		for (EmpAnualLeaveSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.com.ecopharma.emp.model.EmpAnualLeave"));

	public EmpAnualLeaveModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _empAnualLeaveId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEmpAnualLeaveId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _empAnualLeaveId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return EmpAnualLeave.class;
	}

	@Override
	public String getModelClassName() {
		return EmpAnualLeave.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("empAnualLeaveId", getEmpAnualLeaveId());
		attributes.put("empId", getEmpId());
		attributes.put("noOfAnualLeave", getNoOfAnualLeave());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long empAnualLeaveId = (Long)attributes.get("empAnualLeaveId");

		if (empAnualLeaveId != null) {
			setEmpAnualLeaveId(empAnualLeaveId);
		}

		Long empId = (Long)attributes.get("empId");

		if (empId != null) {
			setEmpId(empId);
		}

		Double noOfAnualLeave = (Double)attributes.get("noOfAnualLeave");

		if (noOfAnualLeave != null) {
			setNoOfAnualLeave(noOfAnualLeave);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}
	}

	@JSON
	@Override
	public long getEmpAnualLeaveId() {
		return _empAnualLeaveId;
	}

	@Override
	public void setEmpAnualLeaveId(long empAnualLeaveId) {
		_empAnualLeaveId = empAnualLeaveId;
	}

	@JSON
	@Override
	public long getEmpId() {
		return _empId;
	}

	@Override
	public void setEmpId(long empId) {
		_empId = empId;
	}

	@JSON
	@Override
	public double getNoOfAnualLeave() {
		return _noOfAnualLeave;
	}

	@Override
	public void setNoOfAnualLeave(double noOfAnualLeave) {
		_noOfAnualLeave = noOfAnualLeave;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			EmpAnualLeave.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public EmpAnualLeave toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (EmpAnualLeave)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EmpAnualLeaveImpl empAnualLeaveImpl = new EmpAnualLeaveImpl();

		empAnualLeaveImpl.setEmpAnualLeaveId(getEmpAnualLeaveId());
		empAnualLeaveImpl.setEmpId(getEmpId());
		empAnualLeaveImpl.setNoOfAnualLeave(getNoOfAnualLeave());
		empAnualLeaveImpl.setGroupId(getGroupId());
		empAnualLeaveImpl.setCompanyId(getCompanyId());
		empAnualLeaveImpl.setUserId(getUserId());
		empAnualLeaveImpl.setUserName(getUserName());
		empAnualLeaveImpl.setCreateDate(getCreateDate());
		empAnualLeaveImpl.setModifiedDate(getModifiedDate());

		empAnualLeaveImpl.resetOriginalValues();

		return empAnualLeaveImpl;
	}

	@Override
	public int compareTo(EmpAnualLeave empAnualLeave) {
		long primaryKey = empAnualLeave.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof EmpAnualLeave)) {
			return false;
		}

		EmpAnualLeave empAnualLeave = (EmpAnualLeave)obj;

		long primaryKey = empAnualLeave.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<EmpAnualLeave> toCacheModel() {
		EmpAnualLeaveCacheModel empAnualLeaveCacheModel = new EmpAnualLeaveCacheModel();

		empAnualLeaveCacheModel.empAnualLeaveId = getEmpAnualLeaveId();

		empAnualLeaveCacheModel.empId = getEmpId();

		empAnualLeaveCacheModel.noOfAnualLeave = getNoOfAnualLeave();

		empAnualLeaveCacheModel.groupId = getGroupId();

		empAnualLeaveCacheModel.companyId = getCompanyId();

		empAnualLeaveCacheModel.userId = getUserId();

		empAnualLeaveCacheModel.userName = getUserName();

		String userName = empAnualLeaveCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			empAnualLeaveCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			empAnualLeaveCacheModel.createDate = createDate.getTime();
		}
		else {
			empAnualLeaveCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			empAnualLeaveCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			empAnualLeaveCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return empAnualLeaveCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{empAnualLeaveId=");
		sb.append(getEmpAnualLeaveId());
		sb.append(", empId=");
		sb.append(getEmpId());
		sb.append(", noOfAnualLeave=");
		sb.append(getNoOfAnualLeave());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("vn.com.ecopharma.emp.model.EmpAnualLeave");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>empAnualLeaveId</column-name><column-value><![CDATA[");
		sb.append(getEmpAnualLeaveId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>empId</column-name><column-value><![CDATA[");
		sb.append(getEmpId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>noOfAnualLeave</column-name><column-value><![CDATA[");
		sb.append(getNoOfAnualLeave());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = EmpAnualLeave.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			EmpAnualLeave.class
		};
	private long _empAnualLeaveId;
	private long _empId;
	private double _noOfAnualLeave;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private EmpAnualLeave _escapedModel;
}