/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.com.ecopharma.emp.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import vn.com.ecopharma.emp.model.EmpConcurrentTitles;
import vn.com.ecopharma.emp.model.EmpConcurrentTitlesModel;
import vn.com.ecopharma.emp.model.EmpConcurrentTitlesSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the EmpConcurrentTitles service. Represents a row in the &quot;eco_em_portlet_EmpConcurrentTitles&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.com.ecopharma.emp.model.EmpConcurrentTitlesModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EmpConcurrentTitlesImpl}.
 * </p>
 *
 * @author tvt
 * @see EmpConcurrentTitlesImpl
 * @see vn.com.ecopharma.emp.model.EmpConcurrentTitles
 * @see vn.com.ecopharma.emp.model.EmpConcurrentTitlesModel
 * @generated
 */
@JSON(strict = true)
public class EmpConcurrentTitlesModelImpl extends BaseModelImpl<EmpConcurrentTitles>
	implements EmpConcurrentTitlesModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a emp concurrent titles model instance should use the {@link vn.com.ecopharma.emp.model.EmpConcurrentTitles} interface instead.
	 */
	public static final String TABLE_NAME = "eco_em_portlet_EmpConcurrentTitles";
	public static final Object[][] TABLE_COLUMNS = {
			{ "empConcurrentTitlesId", Types.BIGINT },
			{ "empId", Types.BIGINT },
			{ "titlesId", Types.BIGINT },
			{ "unitGroupId", Types.BIGINT },
			{ "unitId", Types.BIGINT },
			{ "departmentId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table eco_em_portlet_EmpConcurrentTitles (empConcurrentTitlesId LONG not null primary key,empId LONG,titlesId LONG,unitGroupId LONG,unitId LONG,departmentId LONG,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table eco_em_portlet_EmpConcurrentTitles";
	public static final String ORDER_BY_JPQL = " ORDER BY empConcurrentTitles.empConcurrentTitlesId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY eco_em_portlet_EmpConcurrentTitles.empConcurrentTitlesId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.com.ecopharma.emp.model.EmpConcurrentTitles"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.com.ecopharma.emp.model.EmpConcurrentTitles"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.vn.com.ecopharma.emp.model.EmpConcurrentTitles"),
			true);
	public static long EMPID_COLUMN_BITMASK = 1L;
	public static long TITLESID_COLUMN_BITMASK = 2L;
	public static long EMPCONCURRENTTITLESID_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static EmpConcurrentTitles toModel(EmpConcurrentTitlesSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		EmpConcurrentTitles model = new EmpConcurrentTitlesImpl();

		model.setEmpConcurrentTitlesId(soapModel.getEmpConcurrentTitlesId());
		model.setEmpId(soapModel.getEmpId());
		model.setTitlesId(soapModel.getTitlesId());
		model.setUnitGroupId(soapModel.getUnitGroupId());
		model.setUnitId(soapModel.getUnitId());
		model.setDepartmentId(soapModel.getDepartmentId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<EmpConcurrentTitles> toModels(
		EmpConcurrentTitlesSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<EmpConcurrentTitles> models = new ArrayList<EmpConcurrentTitles>(soapModels.length);

		for (EmpConcurrentTitlesSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.com.ecopharma.emp.model.EmpConcurrentTitles"));

	public EmpConcurrentTitlesModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _empConcurrentTitlesId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEmpConcurrentTitlesId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _empConcurrentTitlesId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return EmpConcurrentTitles.class;
	}

	@Override
	public String getModelClassName() {
		return EmpConcurrentTitles.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("empConcurrentTitlesId", getEmpConcurrentTitlesId());
		attributes.put("empId", getEmpId());
		attributes.put("titlesId", getTitlesId());
		attributes.put("unitGroupId", getUnitGroupId());
		attributes.put("unitId", getUnitId());
		attributes.put("departmentId", getDepartmentId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long empConcurrentTitlesId = (Long)attributes.get(
				"empConcurrentTitlesId");

		if (empConcurrentTitlesId != null) {
			setEmpConcurrentTitlesId(empConcurrentTitlesId);
		}

		Long empId = (Long)attributes.get("empId");

		if (empId != null) {
			setEmpId(empId);
		}

		Long titlesId = (Long)attributes.get("titlesId");

		if (titlesId != null) {
			setTitlesId(titlesId);
		}

		Long unitGroupId = (Long)attributes.get("unitGroupId");

		if (unitGroupId != null) {
			setUnitGroupId(unitGroupId);
		}

		Long unitId = (Long)attributes.get("unitId");

		if (unitId != null) {
			setUnitId(unitId);
		}

		Long departmentId = (Long)attributes.get("departmentId");

		if (departmentId != null) {
			setDepartmentId(departmentId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}
	}

	@JSON
	@Override
	public long getEmpConcurrentTitlesId() {
		return _empConcurrentTitlesId;
	}

	@Override
	public void setEmpConcurrentTitlesId(long empConcurrentTitlesId) {
		_empConcurrentTitlesId = empConcurrentTitlesId;
	}

	@JSON
	@Override
	public long getEmpId() {
		return _empId;
	}

	@Override
	public void setEmpId(long empId) {
		_columnBitmask |= EMPID_COLUMN_BITMASK;

		if (!_setOriginalEmpId) {
			_setOriginalEmpId = true;

			_originalEmpId = _empId;
		}

		_empId = empId;
	}

	public long getOriginalEmpId() {
		return _originalEmpId;
	}

	@JSON
	@Override
	public long getTitlesId() {
		return _titlesId;
	}

	@Override
	public void setTitlesId(long titlesId) {
		_columnBitmask |= TITLESID_COLUMN_BITMASK;

		if (!_setOriginalTitlesId) {
			_setOriginalTitlesId = true;

			_originalTitlesId = _titlesId;
		}

		_titlesId = titlesId;
	}

	public long getOriginalTitlesId() {
		return _originalTitlesId;
	}

	@JSON
	@Override
	public long getUnitGroupId() {
		return _unitGroupId;
	}

	@Override
	public void setUnitGroupId(long unitGroupId) {
		_unitGroupId = unitGroupId;
	}

	@JSON
	@Override
	public long getUnitId() {
		return _unitId;
	}

	@Override
	public void setUnitId(long unitId) {
		_unitId = unitId;
	}

	@JSON
	@Override
	public long getDepartmentId() {
		return _departmentId;
	}

	@Override
	public void setDepartmentId(long departmentId) {
		_departmentId = departmentId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			EmpConcurrentTitles.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public EmpConcurrentTitles toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (EmpConcurrentTitles)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EmpConcurrentTitlesImpl empConcurrentTitlesImpl = new EmpConcurrentTitlesImpl();

		empConcurrentTitlesImpl.setEmpConcurrentTitlesId(getEmpConcurrentTitlesId());
		empConcurrentTitlesImpl.setEmpId(getEmpId());
		empConcurrentTitlesImpl.setTitlesId(getTitlesId());
		empConcurrentTitlesImpl.setUnitGroupId(getUnitGroupId());
		empConcurrentTitlesImpl.setUnitId(getUnitId());
		empConcurrentTitlesImpl.setDepartmentId(getDepartmentId());
		empConcurrentTitlesImpl.setGroupId(getGroupId());
		empConcurrentTitlesImpl.setCompanyId(getCompanyId());
		empConcurrentTitlesImpl.setUserId(getUserId());
		empConcurrentTitlesImpl.setUserName(getUserName());
		empConcurrentTitlesImpl.setCreateDate(getCreateDate());
		empConcurrentTitlesImpl.setModifiedDate(getModifiedDate());

		empConcurrentTitlesImpl.resetOriginalValues();

		return empConcurrentTitlesImpl;
	}

	@Override
	public int compareTo(EmpConcurrentTitles empConcurrentTitles) {
		long primaryKey = empConcurrentTitles.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof EmpConcurrentTitles)) {
			return false;
		}

		EmpConcurrentTitles empConcurrentTitles = (EmpConcurrentTitles)obj;

		long primaryKey = empConcurrentTitles.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		EmpConcurrentTitlesModelImpl empConcurrentTitlesModelImpl = this;

		empConcurrentTitlesModelImpl._originalEmpId = empConcurrentTitlesModelImpl._empId;

		empConcurrentTitlesModelImpl._setOriginalEmpId = false;

		empConcurrentTitlesModelImpl._originalTitlesId = empConcurrentTitlesModelImpl._titlesId;

		empConcurrentTitlesModelImpl._setOriginalTitlesId = false;

		empConcurrentTitlesModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<EmpConcurrentTitles> toCacheModel() {
		EmpConcurrentTitlesCacheModel empConcurrentTitlesCacheModel = new EmpConcurrentTitlesCacheModel();

		empConcurrentTitlesCacheModel.empConcurrentTitlesId = getEmpConcurrentTitlesId();

		empConcurrentTitlesCacheModel.empId = getEmpId();

		empConcurrentTitlesCacheModel.titlesId = getTitlesId();

		empConcurrentTitlesCacheModel.unitGroupId = getUnitGroupId();

		empConcurrentTitlesCacheModel.unitId = getUnitId();

		empConcurrentTitlesCacheModel.departmentId = getDepartmentId();

		empConcurrentTitlesCacheModel.groupId = getGroupId();

		empConcurrentTitlesCacheModel.companyId = getCompanyId();

		empConcurrentTitlesCacheModel.userId = getUserId();

		empConcurrentTitlesCacheModel.userName = getUserName();

		String userName = empConcurrentTitlesCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			empConcurrentTitlesCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			empConcurrentTitlesCacheModel.createDate = createDate.getTime();
		}
		else {
			empConcurrentTitlesCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			empConcurrentTitlesCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			empConcurrentTitlesCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return empConcurrentTitlesCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(25);

		sb.append("{empConcurrentTitlesId=");
		sb.append(getEmpConcurrentTitlesId());
		sb.append(", empId=");
		sb.append(getEmpId());
		sb.append(", titlesId=");
		sb.append(getTitlesId());
		sb.append(", unitGroupId=");
		sb.append(getUnitGroupId());
		sb.append(", unitId=");
		sb.append(getUnitId());
		sb.append(", departmentId=");
		sb.append(getDepartmentId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(40);

		sb.append("<model><model-name>");
		sb.append("vn.com.ecopharma.emp.model.EmpConcurrentTitles");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>empConcurrentTitlesId</column-name><column-value><![CDATA[");
		sb.append(getEmpConcurrentTitlesId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>empId</column-name><column-value><![CDATA[");
		sb.append(getEmpId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>titlesId</column-name><column-value><![CDATA[");
		sb.append(getTitlesId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>unitGroupId</column-name><column-value><![CDATA[");
		sb.append(getUnitGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>unitId</column-name><column-value><![CDATA[");
		sb.append(getUnitId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>departmentId</column-name><column-value><![CDATA[");
		sb.append(getDepartmentId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = EmpConcurrentTitles.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			EmpConcurrentTitles.class
		};
	private long _empConcurrentTitlesId;
	private long _empId;
	private long _originalEmpId;
	private boolean _setOriginalEmpId;
	private long _titlesId;
	private long _originalTitlesId;
	private boolean _setOriginalTitlesId;
	private long _unitGroupId;
	private long _unitId;
	private long _departmentId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private long _columnBitmask;
	private EmpConcurrentTitles _escapedModel;
}