/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.com.ecopharma.emp.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import vn.com.ecopharma.emp.model.EmpLaborContract;
import vn.com.ecopharma.emp.model.EmpLaborContractModel;
import vn.com.ecopharma.emp.model.EmpLaborContractSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the EmpLaborContract service. Represents a row in the &quot;eco_em_portlet_EmpLaborContract&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.com.ecopharma.emp.model.EmpLaborContractModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EmpLaborContractImpl}.
 * </p>
 *
 * @author tvt
 * @see EmpLaborContractImpl
 * @see vn.com.ecopharma.emp.model.EmpLaborContract
 * @see vn.com.ecopharma.emp.model.EmpLaborContractModel
 * @generated
 */
@JSON(strict = true)
public class EmpLaborContractModelImpl extends BaseModelImpl<EmpLaborContract>
	implements EmpLaborContractModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a emp labor contract model instance should use the {@link vn.com.ecopharma.emp.model.EmpLaborContract} interface instead.
	 */
	public static final String TABLE_NAME = "eco_em_portlet_EmpLaborContract";
	public static final Object[][] TABLE_COLUMNS = {
			{ "empLaborContractId", Types.BIGINT },
			{ "empId", Types.BIGINT },
			{ "laborContractSignedDate", Types.TIMESTAMP },
			{ "laborContractExpiredDate", Types.TIMESTAMP },
			{ "laborContractSignedType", Types.VARCHAR },
			{ "signedTimes", Types.INTEGER },
			{ "latest", Types.BOOLEAN },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table eco_em_portlet_EmpLaborContract (empLaborContractId LONG not null primary key,empId LONG,laborContractSignedDate DATE null,laborContractExpiredDate DATE null,laborContractSignedType VARCHAR(75) null,signedTimes INTEGER,latest BOOLEAN,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table eco_em_portlet_EmpLaborContract";
	public static final String ORDER_BY_JPQL = " ORDER BY empLaborContract.empLaborContractId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY eco_em_portlet_EmpLaborContract.empLaborContractId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.com.ecopharma.emp.model.EmpLaborContract"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.com.ecopharma.emp.model.EmpLaborContract"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.vn.com.ecopharma.emp.model.EmpLaborContract"),
			true);
	public static long EMPID_COLUMN_BITMASK = 1L;
	public static long EMPLABORCONTRACTID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static EmpLaborContract toModel(EmpLaborContractSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		EmpLaborContract model = new EmpLaborContractImpl();

		model.setEmpLaborContractId(soapModel.getEmpLaborContractId());
		model.setEmpId(soapModel.getEmpId());
		model.setLaborContractSignedDate(soapModel.getLaborContractSignedDate());
		model.setLaborContractExpiredDate(soapModel.getLaborContractExpiredDate());
		model.setLaborContractSignedType(soapModel.getLaborContractSignedType());
		model.setSignedTimes(soapModel.getSignedTimes());
		model.setLatest(soapModel.getLatest());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<EmpLaborContract> toModels(
		EmpLaborContractSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<EmpLaborContract> models = new ArrayList<EmpLaborContract>(soapModels.length);

		for (EmpLaborContractSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.com.ecopharma.emp.model.EmpLaborContract"));

	public EmpLaborContractModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _empLaborContractId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEmpLaborContractId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _empLaborContractId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return EmpLaborContract.class;
	}

	@Override
	public String getModelClassName() {
		return EmpLaborContract.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("empLaborContractId", getEmpLaborContractId());
		attributes.put("empId", getEmpId());
		attributes.put("laborContractSignedDate", getLaborContractSignedDate());
		attributes.put("laborContractExpiredDate", getLaborContractExpiredDate());
		attributes.put("laborContractSignedType", getLaborContractSignedType());
		attributes.put("signedTimes", getSignedTimes());
		attributes.put("latest", getLatest());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long empLaborContractId = (Long)attributes.get("empLaborContractId");

		if (empLaborContractId != null) {
			setEmpLaborContractId(empLaborContractId);
		}

		Long empId = (Long)attributes.get("empId");

		if (empId != null) {
			setEmpId(empId);
		}

		Date laborContractSignedDate = (Date)attributes.get(
				"laborContractSignedDate");

		if (laborContractSignedDate != null) {
			setLaborContractSignedDate(laborContractSignedDate);
		}

		Date laborContractExpiredDate = (Date)attributes.get(
				"laborContractExpiredDate");

		if (laborContractExpiredDate != null) {
			setLaborContractExpiredDate(laborContractExpiredDate);
		}

		String laborContractSignedType = (String)attributes.get(
				"laborContractSignedType");

		if (laborContractSignedType != null) {
			setLaborContractSignedType(laborContractSignedType);
		}

		Integer signedTimes = (Integer)attributes.get("signedTimes");

		if (signedTimes != null) {
			setSignedTimes(signedTimes);
		}

		Boolean latest = (Boolean)attributes.get("latest");

		if (latest != null) {
			setLatest(latest);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}
	}

	@JSON
	@Override
	public long getEmpLaborContractId() {
		return _empLaborContractId;
	}

	@Override
	public void setEmpLaborContractId(long empLaborContractId) {
		_empLaborContractId = empLaborContractId;
	}

	@JSON
	@Override
	public long getEmpId() {
		return _empId;
	}

	@Override
	public void setEmpId(long empId) {
		_columnBitmask |= EMPID_COLUMN_BITMASK;

		if (!_setOriginalEmpId) {
			_setOriginalEmpId = true;

			_originalEmpId = _empId;
		}

		_empId = empId;
	}

	public long getOriginalEmpId() {
		return _originalEmpId;
	}

	@JSON
	@Override
	public Date getLaborContractSignedDate() {
		return _laborContractSignedDate;
	}

	@Override
	public void setLaborContractSignedDate(Date laborContractSignedDate) {
		_laborContractSignedDate = laborContractSignedDate;
	}

	@JSON
	@Override
	public Date getLaborContractExpiredDate() {
		return _laborContractExpiredDate;
	}

	@Override
	public void setLaborContractExpiredDate(Date laborContractExpiredDate) {
		_laborContractExpiredDate = laborContractExpiredDate;
	}

	@JSON
	@Override
	public String getLaborContractSignedType() {
		if (_laborContractSignedType == null) {
			return StringPool.BLANK;
		}
		else {
			return _laborContractSignedType;
		}
	}

	@Override
	public void setLaborContractSignedType(String laborContractSignedType) {
		_laborContractSignedType = laborContractSignedType;
	}

	@JSON
	@Override
	public int getSignedTimes() {
		return _signedTimes;
	}

	@Override
	public void setSignedTimes(int signedTimes) {
		_signedTimes = signedTimes;
	}

	@JSON
	@Override
	public boolean getLatest() {
		return _latest;
	}

	@Override
	public boolean isLatest() {
		return _latest;
	}

	@Override
	public void setLatest(boolean latest) {
		_latest = latest;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			EmpLaborContract.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public EmpLaborContract toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (EmpLaborContract)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EmpLaborContractImpl empLaborContractImpl = new EmpLaborContractImpl();

		empLaborContractImpl.setEmpLaborContractId(getEmpLaborContractId());
		empLaborContractImpl.setEmpId(getEmpId());
		empLaborContractImpl.setLaborContractSignedDate(getLaborContractSignedDate());
		empLaborContractImpl.setLaborContractExpiredDate(getLaborContractExpiredDate());
		empLaborContractImpl.setLaborContractSignedType(getLaborContractSignedType());
		empLaborContractImpl.setSignedTimes(getSignedTimes());
		empLaborContractImpl.setLatest(getLatest());
		empLaborContractImpl.setGroupId(getGroupId());
		empLaborContractImpl.setCompanyId(getCompanyId());
		empLaborContractImpl.setUserId(getUserId());
		empLaborContractImpl.setUserName(getUserName());
		empLaborContractImpl.setCreateDate(getCreateDate());
		empLaborContractImpl.setModifiedDate(getModifiedDate());

		empLaborContractImpl.resetOriginalValues();

		return empLaborContractImpl;
	}

	@Override
	public int compareTo(EmpLaborContract empLaborContract) {
		long primaryKey = empLaborContract.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof EmpLaborContract)) {
			return false;
		}

		EmpLaborContract empLaborContract = (EmpLaborContract)obj;

		long primaryKey = empLaborContract.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		EmpLaborContractModelImpl empLaborContractModelImpl = this;

		empLaborContractModelImpl._originalEmpId = empLaborContractModelImpl._empId;

		empLaborContractModelImpl._setOriginalEmpId = false;

		empLaborContractModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<EmpLaborContract> toCacheModel() {
		EmpLaborContractCacheModel empLaborContractCacheModel = new EmpLaborContractCacheModel();

		empLaborContractCacheModel.empLaborContractId = getEmpLaborContractId();

		empLaborContractCacheModel.empId = getEmpId();

		Date laborContractSignedDate = getLaborContractSignedDate();

		if (laborContractSignedDate != null) {
			empLaborContractCacheModel.laborContractSignedDate = laborContractSignedDate.getTime();
		}
		else {
			empLaborContractCacheModel.laborContractSignedDate = Long.MIN_VALUE;
		}

		Date laborContractExpiredDate = getLaborContractExpiredDate();

		if (laborContractExpiredDate != null) {
			empLaborContractCacheModel.laborContractExpiredDate = laborContractExpiredDate.getTime();
		}
		else {
			empLaborContractCacheModel.laborContractExpiredDate = Long.MIN_VALUE;
		}

		empLaborContractCacheModel.laborContractSignedType = getLaborContractSignedType();

		String laborContractSignedType = empLaborContractCacheModel.laborContractSignedType;

		if ((laborContractSignedType != null) &&
				(laborContractSignedType.length() == 0)) {
			empLaborContractCacheModel.laborContractSignedType = null;
		}

		empLaborContractCacheModel.signedTimes = getSignedTimes();

		empLaborContractCacheModel.latest = getLatest();

		empLaborContractCacheModel.groupId = getGroupId();

		empLaborContractCacheModel.companyId = getCompanyId();

		empLaborContractCacheModel.userId = getUserId();

		empLaborContractCacheModel.userName = getUserName();

		String userName = empLaborContractCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			empLaborContractCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			empLaborContractCacheModel.createDate = createDate.getTime();
		}
		else {
			empLaborContractCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			empLaborContractCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			empLaborContractCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return empLaborContractCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(27);

		sb.append("{empLaborContractId=");
		sb.append(getEmpLaborContractId());
		sb.append(", empId=");
		sb.append(getEmpId());
		sb.append(", laborContractSignedDate=");
		sb.append(getLaborContractSignedDate());
		sb.append(", laborContractExpiredDate=");
		sb.append(getLaborContractExpiredDate());
		sb.append(", laborContractSignedType=");
		sb.append(getLaborContractSignedType());
		sb.append(", signedTimes=");
		sb.append(getSignedTimes());
		sb.append(", latest=");
		sb.append(getLatest());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(43);

		sb.append("<model><model-name>");
		sb.append("vn.com.ecopharma.emp.model.EmpLaborContract");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>empLaborContractId</column-name><column-value><![CDATA[");
		sb.append(getEmpLaborContractId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>empId</column-name><column-value><![CDATA[");
		sb.append(getEmpId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>laborContractSignedDate</column-name><column-value><![CDATA[");
		sb.append(getLaborContractSignedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>laborContractExpiredDate</column-name><column-value><![CDATA[");
		sb.append(getLaborContractExpiredDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>laborContractSignedType</column-name><column-value><![CDATA[");
		sb.append(getLaborContractSignedType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>signedTimes</column-name><column-value><![CDATA[");
		sb.append(getSignedTimes());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>latest</column-name><column-value><![CDATA[");
		sb.append(getLatest());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = EmpLaborContract.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			EmpLaborContract.class
		};
	private long _empLaborContractId;
	private long _empId;
	private long _originalEmpId;
	private boolean _setOriginalEmpId;
	private Date _laborContractSignedDate;
	private Date _laborContractExpiredDate;
	private String _laborContractSignedType;
	private int _signedTimes;
	private boolean _latest;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private long _columnBitmask;
	private EmpLaborContract _escapedModel;
}