/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.com.ecopharma.emp.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import vn.com.ecopharma.emp.model.ResignationHistory;
import vn.com.ecopharma.emp.model.ResignationHistoryModel;
import vn.com.ecopharma.emp.model.ResignationHistorySoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the ResignationHistory service. Represents a row in the &quot;eco_em_portlet_ResignationHistory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.com.ecopharma.emp.model.ResignationHistoryModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ResignationHistoryImpl}.
 * </p>
 *
 * @author tvt
 * @see ResignationHistoryImpl
 * @see vn.com.ecopharma.emp.model.ResignationHistory
 * @see vn.com.ecopharma.emp.model.ResignationHistoryModel
 * @generated
 */
@JSON(strict = true)
public class ResignationHistoryModelImpl extends BaseModelImpl<ResignationHistory>
	implements ResignationHistoryModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a resignation history model instance should use the {@link vn.com.ecopharma.emp.model.ResignationHistory} interface instead.
	 */
	public static final String TABLE_NAME = "eco_em_portlet_ResignationHistory";
	public static final Object[][] TABLE_COLUMNS = {
			{ "resignationHistoryId", Types.BIGINT },
			{ "employeeId", Types.BIGINT },
			{ "resignedDate", Types.TIMESTAMP },
			{ "resignedType", Types.VARCHAR },
			{ "comment_", Types.VARCHAR },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "deleted", Types.BOOLEAN }
		};
	public static final String TABLE_SQL_CREATE = "create table eco_em_portlet_ResignationHistory (resignationHistoryId LONG not null primary key,employeeId LONG,resignedDate DATE null,resignedType VARCHAR(75) null,comment_ VARCHAR(75) null,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,deleted BOOLEAN)";
	public static final String TABLE_SQL_DROP = "drop table eco_em_portlet_ResignationHistory";
	public static final String ORDER_BY_JPQL = " ORDER BY resignationHistory.resignationHistoryId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY eco_em_portlet_ResignationHistory.resignationHistoryId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.com.ecopharma.emp.model.ResignationHistory"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.com.ecopharma.emp.model.ResignationHistory"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.vn.com.ecopharma.emp.model.ResignationHistory"),
			true);
	public static long EMPLOYEEID_COLUMN_BITMASK = 1L;
	public static long RESIGNATIONHISTORYID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static ResignationHistory toModel(ResignationHistorySoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		ResignationHistory model = new ResignationHistoryImpl();

		model.setResignationHistoryId(soapModel.getResignationHistoryId());
		model.setEmployeeId(soapModel.getEmployeeId());
		model.setResignedDate(soapModel.getResignedDate());
		model.setResignedType(soapModel.getResignedType());
		model.setComment(soapModel.getComment());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setDeleted(soapModel.getDeleted());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<ResignationHistory> toModels(
		ResignationHistorySoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<ResignationHistory> models = new ArrayList<ResignationHistory>(soapModels.length);

		for (ResignationHistorySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.com.ecopharma.emp.model.ResignationHistory"));

	public ResignationHistoryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _resignationHistoryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setResignationHistoryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _resignationHistoryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ResignationHistory.class;
	}

	@Override
	public String getModelClassName() {
		return ResignationHistory.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("resignationHistoryId", getResignationHistoryId());
		attributes.put("employeeId", getEmployeeId());
		attributes.put("resignedDate", getResignedDate());
		attributes.put("resignedType", getResignedType());
		attributes.put("comment", getComment());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("deleted", getDeleted());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long resignationHistoryId = (Long)attributes.get("resignationHistoryId");

		if (resignationHistoryId != null) {
			setResignationHistoryId(resignationHistoryId);
		}

		Long employeeId = (Long)attributes.get("employeeId");

		if (employeeId != null) {
			setEmployeeId(employeeId);
		}

		Date resignedDate = (Date)attributes.get("resignedDate");

		if (resignedDate != null) {
			setResignedDate(resignedDate);
		}

		String resignedType = (String)attributes.get("resignedType");

		if (resignedType != null) {
			setResignedType(resignedType);
		}

		String comment = (String)attributes.get("comment");

		if (comment != null) {
			setComment(comment);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Boolean deleted = (Boolean)attributes.get("deleted");

		if (deleted != null) {
			setDeleted(deleted);
		}
	}

	@JSON
	@Override
	public long getResignationHistoryId() {
		return _resignationHistoryId;
	}

	@Override
	public void setResignationHistoryId(long resignationHistoryId) {
		_resignationHistoryId = resignationHistoryId;
	}

	@JSON
	@Override
	public long getEmployeeId() {
		return _employeeId;
	}

	@Override
	public void setEmployeeId(long employeeId) {
		_columnBitmask |= EMPLOYEEID_COLUMN_BITMASK;

		if (!_setOriginalEmployeeId) {
			_setOriginalEmployeeId = true;

			_originalEmployeeId = _employeeId;
		}

		_employeeId = employeeId;
	}

	public long getOriginalEmployeeId() {
		return _originalEmployeeId;
	}

	@JSON
	@Override
	public Date getResignedDate() {
		return _resignedDate;
	}

	@Override
	public void setResignedDate(Date resignedDate) {
		_resignedDate = resignedDate;
	}

	@JSON
	@Override
	public String getResignedType() {
		if (_resignedType == null) {
			return StringPool.BLANK;
		}
		else {
			return _resignedType;
		}
	}

	@Override
	public void setResignedType(String resignedType) {
		_resignedType = resignedType;
	}

	@JSON
	@Override
	public String getComment() {
		if (_comment == null) {
			return StringPool.BLANK;
		}
		else {
			return _comment;
		}
	}

	@Override
	public void setComment(String comment) {
		_comment = comment;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public boolean getDeleted() {
		return _deleted;
	}

	@Override
	public boolean isDeleted() {
		return _deleted;
	}

	@Override
	public void setDeleted(boolean deleted) {
		_deleted = deleted;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			ResignationHistory.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ResignationHistory toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ResignationHistory)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ResignationHistoryImpl resignationHistoryImpl = new ResignationHistoryImpl();

		resignationHistoryImpl.setResignationHistoryId(getResignationHistoryId());
		resignationHistoryImpl.setEmployeeId(getEmployeeId());
		resignationHistoryImpl.setResignedDate(getResignedDate());
		resignationHistoryImpl.setResignedType(getResignedType());
		resignationHistoryImpl.setComment(getComment());
		resignationHistoryImpl.setGroupId(getGroupId());
		resignationHistoryImpl.setCompanyId(getCompanyId());
		resignationHistoryImpl.setUserId(getUserId());
		resignationHistoryImpl.setUserName(getUserName());
		resignationHistoryImpl.setCreateDate(getCreateDate());
		resignationHistoryImpl.setModifiedDate(getModifiedDate());
		resignationHistoryImpl.setDeleted(getDeleted());

		resignationHistoryImpl.resetOriginalValues();

		return resignationHistoryImpl;
	}

	@Override
	public int compareTo(ResignationHistory resignationHistory) {
		long primaryKey = resignationHistory.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ResignationHistory)) {
			return false;
		}

		ResignationHistory resignationHistory = (ResignationHistory)obj;

		long primaryKey = resignationHistory.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		ResignationHistoryModelImpl resignationHistoryModelImpl = this;

		resignationHistoryModelImpl._originalEmployeeId = resignationHistoryModelImpl._employeeId;

		resignationHistoryModelImpl._setOriginalEmployeeId = false;

		resignationHistoryModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ResignationHistory> toCacheModel() {
		ResignationHistoryCacheModel resignationHistoryCacheModel = new ResignationHistoryCacheModel();

		resignationHistoryCacheModel.resignationHistoryId = getResignationHistoryId();

		resignationHistoryCacheModel.employeeId = getEmployeeId();

		Date resignedDate = getResignedDate();

		if (resignedDate != null) {
			resignationHistoryCacheModel.resignedDate = resignedDate.getTime();
		}
		else {
			resignationHistoryCacheModel.resignedDate = Long.MIN_VALUE;
		}

		resignationHistoryCacheModel.resignedType = getResignedType();

		String resignedType = resignationHistoryCacheModel.resignedType;

		if ((resignedType != null) && (resignedType.length() == 0)) {
			resignationHistoryCacheModel.resignedType = null;
		}

		resignationHistoryCacheModel.comment = getComment();

		String comment = resignationHistoryCacheModel.comment;

		if ((comment != null) && (comment.length() == 0)) {
			resignationHistoryCacheModel.comment = null;
		}

		resignationHistoryCacheModel.groupId = getGroupId();

		resignationHistoryCacheModel.companyId = getCompanyId();

		resignationHistoryCacheModel.userId = getUserId();

		resignationHistoryCacheModel.userName = getUserName();

		String userName = resignationHistoryCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			resignationHistoryCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			resignationHistoryCacheModel.createDate = createDate.getTime();
		}
		else {
			resignationHistoryCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			resignationHistoryCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			resignationHistoryCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		resignationHistoryCacheModel.deleted = getDeleted();

		return resignationHistoryCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(25);

		sb.append("{resignationHistoryId=");
		sb.append(getResignationHistoryId());
		sb.append(", employeeId=");
		sb.append(getEmployeeId());
		sb.append(", resignedDate=");
		sb.append(getResignedDate());
		sb.append(", resignedType=");
		sb.append(getResignedType());
		sb.append(", comment=");
		sb.append(getComment());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", deleted=");
		sb.append(getDeleted());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(40);

		sb.append("<model><model-name>");
		sb.append("vn.com.ecopharma.emp.model.ResignationHistory");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>resignationHistoryId</column-name><column-value><![CDATA[");
		sb.append(getResignationHistoryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>employeeId</column-name><column-value><![CDATA[");
		sb.append(getEmployeeId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>resignedDate</column-name><column-value><![CDATA[");
		sb.append(getResignedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>resignedType</column-name><column-value><![CDATA[");
		sb.append(getResignedType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>comment</column-name><column-value><![CDATA[");
		sb.append(getComment());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>deleted</column-name><column-value><![CDATA[");
		sb.append(getDeleted());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = ResignationHistory.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			ResignationHistory.class
		};
	private long _resignationHistoryId;
	private long _employeeId;
	private long _originalEmployeeId;
	private boolean _setOriginalEmployeeId;
	private Date _resignedDate;
	private String _resignedType;
	private String _comment;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _deleted;
	private long _columnBitmask;
	private ResignationHistory _escapedModel;
}