/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.com.ecopharma.emp.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import vn.com.ecopharma.emp.model.ResourceConfig;
import vn.com.ecopharma.emp.model.ResourceConfigModel;
import vn.com.ecopharma.emp.model.ResourceConfigSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the ResourceConfig service. Represents a row in the &quot;eco_em_portlet_ResourceConfig&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.com.ecopharma.emp.model.ResourceConfigModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ResourceConfigImpl}.
 * </p>
 *
 * @author tvt
 * @see ResourceConfigImpl
 * @see vn.com.ecopharma.emp.model.ResourceConfig
 * @see vn.com.ecopharma.emp.model.ResourceConfigModel
 * @generated
 */
@JSON(strict = true)
public class ResourceConfigModelImpl extends BaseModelImpl<ResourceConfig>
	implements ResourceConfigModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a resource config model instance should use the {@link vn.com.ecopharma.emp.model.ResourceConfig} interface instead.
	 */
	public static final String TABLE_NAME = "eco_em_portlet_ResourceConfig";
	public static final Object[][] TABLE_COLUMNS = {
			{ "resourceConfigId", Types.BIGINT },
			{ "key_", Types.VARCHAR },
			{ "value", Types.VARCHAR },
			{ "type_", Types.VARCHAR },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table eco_em_portlet_ResourceConfig (resourceConfigId LONG not null primary key,key_ VARCHAR(75) null,value VARCHAR(2000) null,type_ VARCHAR(75) null,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table eco_em_portlet_ResourceConfig";
	public static final String ORDER_BY_JPQL = " ORDER BY resourceConfig.resourceConfigId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY eco_em_portlet_ResourceConfig.resourceConfigId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.com.ecopharma.emp.model.ResourceConfig"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.com.ecopharma.emp.model.ResourceConfig"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.vn.com.ecopharma.emp.model.ResourceConfig"),
			true);
	public static long KEY_COLUMN_BITMASK = 1L;
	public static long TYPE_COLUMN_BITMASK = 2L;
	public static long RESOURCECONFIGID_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static ResourceConfig toModel(ResourceConfigSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		ResourceConfig model = new ResourceConfigImpl();

		model.setResourceConfigId(soapModel.getResourceConfigId());
		model.setKey(soapModel.getKey());
		model.setValue(soapModel.getValue());
		model.setType(soapModel.getType());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<ResourceConfig> toModels(ResourceConfigSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<ResourceConfig> models = new ArrayList<ResourceConfig>(soapModels.length);

		for (ResourceConfigSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.com.ecopharma.emp.model.ResourceConfig"));

	public ResourceConfigModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _resourceConfigId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setResourceConfigId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _resourceConfigId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ResourceConfig.class;
	}

	@Override
	public String getModelClassName() {
		return ResourceConfig.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("resourceConfigId", getResourceConfigId());
		attributes.put("key", getKey());
		attributes.put("value", getValue());
		attributes.put("type", getType());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long resourceConfigId = (Long)attributes.get("resourceConfigId");

		if (resourceConfigId != null) {
			setResourceConfigId(resourceConfigId);
		}

		String key = (String)attributes.get("key");

		if (key != null) {
			setKey(key);
		}

		String value = (String)attributes.get("value");

		if (value != null) {
			setValue(value);
		}

		String type = (String)attributes.get("type");

		if (type != null) {
			setType(type);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}
	}

	@JSON
	@Override
	public long getResourceConfigId() {
		return _resourceConfigId;
	}

	@Override
	public void setResourceConfigId(long resourceConfigId) {
		_resourceConfigId = resourceConfigId;
	}

	@JSON
	@Override
	public String getKey() {
		if (_key == null) {
			return StringPool.BLANK;
		}
		else {
			return _key;
		}
	}

	@Override
	public void setKey(String key) {
		_columnBitmask |= KEY_COLUMN_BITMASK;

		if (_originalKey == null) {
			_originalKey = _key;
		}

		_key = key;
	}

	public String getOriginalKey() {
		return GetterUtil.getString(_originalKey);
	}

	@JSON
	@Override
	public String getValue() {
		if (_value == null) {
			return StringPool.BLANK;
		}
		else {
			return _value;
		}
	}

	@Override
	public void setValue(String value) {
		_value = value;
	}

	@JSON
	@Override
	public String getType() {
		if (_type == null) {
			return StringPool.BLANK;
		}
		else {
			return _type;
		}
	}

	@Override
	public void setType(String type) {
		_columnBitmask |= TYPE_COLUMN_BITMASK;

		if (_originalType == null) {
			_originalType = _type;
		}

		_type = type;
	}

	public String getOriginalType() {
		return GetterUtil.getString(_originalType);
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			ResourceConfig.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ResourceConfig toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ResourceConfig)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ResourceConfigImpl resourceConfigImpl = new ResourceConfigImpl();

		resourceConfigImpl.setResourceConfigId(getResourceConfigId());
		resourceConfigImpl.setKey(getKey());
		resourceConfigImpl.setValue(getValue());
		resourceConfigImpl.setType(getType());
		resourceConfigImpl.setGroupId(getGroupId());
		resourceConfigImpl.setCompanyId(getCompanyId());
		resourceConfigImpl.setUserId(getUserId());
		resourceConfigImpl.setUserName(getUserName());
		resourceConfigImpl.setCreateDate(getCreateDate());
		resourceConfigImpl.setModifiedDate(getModifiedDate());

		resourceConfigImpl.resetOriginalValues();

		return resourceConfigImpl;
	}

	@Override
	public int compareTo(ResourceConfig resourceConfig) {
		long primaryKey = resourceConfig.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ResourceConfig)) {
			return false;
		}

		ResourceConfig resourceConfig = (ResourceConfig)obj;

		long primaryKey = resourceConfig.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		ResourceConfigModelImpl resourceConfigModelImpl = this;

		resourceConfigModelImpl._originalKey = resourceConfigModelImpl._key;

		resourceConfigModelImpl._originalType = resourceConfigModelImpl._type;

		resourceConfigModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ResourceConfig> toCacheModel() {
		ResourceConfigCacheModel resourceConfigCacheModel = new ResourceConfigCacheModel();

		resourceConfigCacheModel.resourceConfigId = getResourceConfigId();

		resourceConfigCacheModel.key = getKey();

		String key = resourceConfigCacheModel.key;

		if ((key != null) && (key.length() == 0)) {
			resourceConfigCacheModel.key = null;
		}

		resourceConfigCacheModel.value = getValue();

		String value = resourceConfigCacheModel.value;

		if ((value != null) && (value.length() == 0)) {
			resourceConfigCacheModel.value = null;
		}

		resourceConfigCacheModel.type = getType();

		String type = resourceConfigCacheModel.type;

		if ((type != null) && (type.length() == 0)) {
			resourceConfigCacheModel.type = null;
		}

		resourceConfigCacheModel.groupId = getGroupId();

		resourceConfigCacheModel.companyId = getCompanyId();

		resourceConfigCacheModel.userId = getUserId();

		resourceConfigCacheModel.userName = getUserName();

		String userName = resourceConfigCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			resourceConfigCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			resourceConfigCacheModel.createDate = createDate.getTime();
		}
		else {
			resourceConfigCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			resourceConfigCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			resourceConfigCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return resourceConfigCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(21);

		sb.append("{resourceConfigId=");
		sb.append(getResourceConfigId());
		sb.append(", key=");
		sb.append(getKey());
		sb.append(", value=");
		sb.append(getValue());
		sb.append(", type=");
		sb.append(getType());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(34);

		sb.append("<model><model-name>");
		sb.append("vn.com.ecopharma.emp.model.ResourceConfig");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>resourceConfigId</column-name><column-value><![CDATA[");
		sb.append(getResourceConfigId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>key</column-name><column-value><![CDATA[");
		sb.append(getKey());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>value</column-name><column-value><![CDATA[");
		sb.append(getValue());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>type</column-name><column-value><![CDATA[");
		sb.append(getType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = ResourceConfig.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			ResourceConfig.class
		};
	private long _resourceConfigId;
	private String _key;
	private String _originalKey;
	private String _value;
	private String _type;
	private String _originalType;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private long _columnBitmask;
	private ResourceConfig _escapedModel;
}