/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.com.ecopharma.emp.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import vn.com.ecopharma.emp.model.TitlesUnitUnitGroup;
import vn.com.ecopharma.emp.model.TitlesUnitUnitGroupModel;
import vn.com.ecopharma.emp.model.TitlesUnitUnitGroupSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the TitlesUnitUnitGroup service. Represents a row in the &quot;eco_em_portlet_TitlesUnitUnitGroup&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.com.ecopharma.emp.model.TitlesUnitUnitGroupModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TitlesUnitUnitGroupImpl}.
 * </p>
 *
 * @author tvt
 * @see TitlesUnitUnitGroupImpl
 * @see vn.com.ecopharma.emp.model.TitlesUnitUnitGroup
 * @see vn.com.ecopharma.emp.model.TitlesUnitUnitGroupModel
 * @generated
 */
@JSON(strict = true)
public class TitlesUnitUnitGroupModelImpl extends BaseModelImpl<TitlesUnitUnitGroup>
	implements TitlesUnitUnitGroupModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a titles unit unit group model instance should use the {@link vn.com.ecopharma.emp.model.TitlesUnitUnitGroup} interface instead.
	 */
	public static final String TABLE_NAME = "eco_em_portlet_TitlesUnitUnitGroup";
	public static final Object[][] TABLE_COLUMNS = {
			{ "titlesUnitUnitGroupId", Types.BIGINT },
			{ "titlesId", Types.BIGINT },
			{ "unitId", Types.BIGINT },
			{ "unitGroupId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table eco_em_portlet_TitlesUnitUnitGroup (titlesUnitUnitGroupId LONG not null primary key,titlesId LONG,unitId LONG,unitGroupId LONG,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table eco_em_portlet_TitlesUnitUnitGroup";
	public static final String ORDER_BY_JPQL = " ORDER BY titlesUnitUnitGroup.titlesUnitUnitGroupId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY eco_em_portlet_TitlesUnitUnitGroup.titlesUnitUnitGroupId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.com.ecopharma.emp.model.TitlesUnitUnitGroup"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.com.ecopharma.emp.model.TitlesUnitUnitGroup"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.vn.com.ecopharma.emp.model.TitlesUnitUnitGroup"),
			true);
	public static long TITLESID_COLUMN_BITMASK = 1L;
	public static long UNITGROUPID_COLUMN_BITMASK = 2L;
	public static long UNITID_COLUMN_BITMASK = 4L;
	public static long TITLESUNITUNITGROUPID_COLUMN_BITMASK = 8L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static TitlesUnitUnitGroup toModel(TitlesUnitUnitGroupSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		TitlesUnitUnitGroup model = new TitlesUnitUnitGroupImpl();

		model.setTitlesUnitUnitGroupId(soapModel.getTitlesUnitUnitGroupId());
		model.setTitlesId(soapModel.getTitlesId());
		model.setUnitId(soapModel.getUnitId());
		model.setUnitGroupId(soapModel.getUnitGroupId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<TitlesUnitUnitGroup> toModels(
		TitlesUnitUnitGroupSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<TitlesUnitUnitGroup> models = new ArrayList<TitlesUnitUnitGroup>(soapModels.length);

		for (TitlesUnitUnitGroupSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.com.ecopharma.emp.model.TitlesUnitUnitGroup"));

	public TitlesUnitUnitGroupModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _titlesUnitUnitGroupId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTitlesUnitUnitGroupId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _titlesUnitUnitGroupId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TitlesUnitUnitGroup.class;
	}

	@Override
	public String getModelClassName() {
		return TitlesUnitUnitGroup.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("titlesUnitUnitGroupId", getTitlesUnitUnitGroupId());
		attributes.put("titlesId", getTitlesId());
		attributes.put("unitId", getUnitId());
		attributes.put("unitGroupId", getUnitGroupId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long titlesUnitUnitGroupId = (Long)attributes.get(
				"titlesUnitUnitGroupId");

		if (titlesUnitUnitGroupId != null) {
			setTitlesUnitUnitGroupId(titlesUnitUnitGroupId);
		}

		Long titlesId = (Long)attributes.get("titlesId");

		if (titlesId != null) {
			setTitlesId(titlesId);
		}

		Long unitId = (Long)attributes.get("unitId");

		if (unitId != null) {
			setUnitId(unitId);
		}

		Long unitGroupId = (Long)attributes.get("unitGroupId");

		if (unitGroupId != null) {
			setUnitGroupId(unitGroupId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}
	}

	@JSON
	@Override
	public long getTitlesUnitUnitGroupId() {
		return _titlesUnitUnitGroupId;
	}

	@Override
	public void setTitlesUnitUnitGroupId(long titlesUnitUnitGroupId) {
		_titlesUnitUnitGroupId = titlesUnitUnitGroupId;
	}

	@JSON
	@Override
	public long getTitlesId() {
		return _titlesId;
	}

	@Override
	public void setTitlesId(long titlesId) {
		_columnBitmask |= TITLESID_COLUMN_BITMASK;

		if (!_setOriginalTitlesId) {
			_setOriginalTitlesId = true;

			_originalTitlesId = _titlesId;
		}

		_titlesId = titlesId;
	}

	public long getOriginalTitlesId() {
		return _originalTitlesId;
	}

	@JSON
	@Override
	public long getUnitId() {
		return _unitId;
	}

	@Override
	public void setUnitId(long unitId) {
		_columnBitmask |= UNITID_COLUMN_BITMASK;

		if (!_setOriginalUnitId) {
			_setOriginalUnitId = true;

			_originalUnitId = _unitId;
		}

		_unitId = unitId;
	}

	public long getOriginalUnitId() {
		return _originalUnitId;
	}

	@JSON
	@Override
	public long getUnitGroupId() {
		return _unitGroupId;
	}

	@Override
	public void setUnitGroupId(long unitGroupId) {
		_columnBitmask |= UNITGROUPID_COLUMN_BITMASK;

		if (!_setOriginalUnitGroupId) {
			_setOriginalUnitGroupId = true;

			_originalUnitGroupId = _unitGroupId;
		}

		_unitGroupId = unitGroupId;
	}

	public long getOriginalUnitGroupId() {
		return _originalUnitGroupId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			TitlesUnitUnitGroup.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TitlesUnitUnitGroup toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (TitlesUnitUnitGroup)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TitlesUnitUnitGroupImpl titlesUnitUnitGroupImpl = new TitlesUnitUnitGroupImpl();

		titlesUnitUnitGroupImpl.setTitlesUnitUnitGroupId(getTitlesUnitUnitGroupId());
		titlesUnitUnitGroupImpl.setTitlesId(getTitlesId());
		titlesUnitUnitGroupImpl.setUnitId(getUnitId());
		titlesUnitUnitGroupImpl.setUnitGroupId(getUnitGroupId());
		titlesUnitUnitGroupImpl.setGroupId(getGroupId());
		titlesUnitUnitGroupImpl.setCompanyId(getCompanyId());
		titlesUnitUnitGroupImpl.setUserId(getUserId());
		titlesUnitUnitGroupImpl.setUserName(getUserName());
		titlesUnitUnitGroupImpl.setCreateDate(getCreateDate());
		titlesUnitUnitGroupImpl.setModifiedDate(getModifiedDate());

		titlesUnitUnitGroupImpl.resetOriginalValues();

		return titlesUnitUnitGroupImpl;
	}

	@Override
	public int compareTo(TitlesUnitUnitGroup titlesUnitUnitGroup) {
		long primaryKey = titlesUnitUnitGroup.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof TitlesUnitUnitGroup)) {
			return false;
		}

		TitlesUnitUnitGroup titlesUnitUnitGroup = (TitlesUnitUnitGroup)obj;

		long primaryKey = titlesUnitUnitGroup.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		TitlesUnitUnitGroupModelImpl titlesUnitUnitGroupModelImpl = this;

		titlesUnitUnitGroupModelImpl._originalTitlesId = titlesUnitUnitGroupModelImpl._titlesId;

		titlesUnitUnitGroupModelImpl._setOriginalTitlesId = false;

		titlesUnitUnitGroupModelImpl._originalUnitId = titlesUnitUnitGroupModelImpl._unitId;

		titlesUnitUnitGroupModelImpl._setOriginalUnitId = false;

		titlesUnitUnitGroupModelImpl._originalUnitGroupId = titlesUnitUnitGroupModelImpl._unitGroupId;

		titlesUnitUnitGroupModelImpl._setOriginalUnitGroupId = false;

		titlesUnitUnitGroupModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<TitlesUnitUnitGroup> toCacheModel() {
		TitlesUnitUnitGroupCacheModel titlesUnitUnitGroupCacheModel = new TitlesUnitUnitGroupCacheModel();

		titlesUnitUnitGroupCacheModel.titlesUnitUnitGroupId = getTitlesUnitUnitGroupId();

		titlesUnitUnitGroupCacheModel.titlesId = getTitlesId();

		titlesUnitUnitGroupCacheModel.unitId = getUnitId();

		titlesUnitUnitGroupCacheModel.unitGroupId = getUnitGroupId();

		titlesUnitUnitGroupCacheModel.groupId = getGroupId();

		titlesUnitUnitGroupCacheModel.companyId = getCompanyId();

		titlesUnitUnitGroupCacheModel.userId = getUserId();

		titlesUnitUnitGroupCacheModel.userName = getUserName();

		String userName = titlesUnitUnitGroupCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			titlesUnitUnitGroupCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			titlesUnitUnitGroupCacheModel.createDate = createDate.getTime();
		}
		else {
			titlesUnitUnitGroupCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			titlesUnitUnitGroupCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			titlesUnitUnitGroupCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return titlesUnitUnitGroupCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(21);

		sb.append("{titlesUnitUnitGroupId=");
		sb.append(getTitlesUnitUnitGroupId());
		sb.append(", titlesId=");
		sb.append(getTitlesId());
		sb.append(", unitId=");
		sb.append(getUnitId());
		sb.append(", unitGroupId=");
		sb.append(getUnitGroupId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(34);

		sb.append("<model><model-name>");
		sb.append("vn.com.ecopharma.emp.model.TitlesUnitUnitGroup");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>titlesUnitUnitGroupId</column-name><column-value><![CDATA[");
		sb.append(getTitlesUnitUnitGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>titlesId</column-name><column-value><![CDATA[");
		sb.append(getTitlesId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>unitId</column-name><column-value><![CDATA[");
		sb.append(getUnitId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>unitGroupId</column-name><column-value><![CDATA[");
		sb.append(getUnitGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = TitlesUnitUnitGroup.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			TitlesUnitUnitGroup.class
		};
	private long _titlesUnitUnitGroupId;
	private long _titlesId;
	private long _originalTitlesId;
	private boolean _setOriginalTitlesId;
	private long _unitId;
	private long _originalUnitId;
	private boolean _setOriginalUnitId;
	private long _unitGroupId;
	private long _originalUnitGroupId;
	private boolean _setOriginalUnitGroupId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private long _columnBitmask;
	private TitlesUnitUnitGroup _escapedModel;
}