/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.com.ecopharma.emp.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import vn.com.ecopharma.emp.model.UnitGroup;
import vn.com.ecopharma.emp.model.UnitGroupModel;
import vn.com.ecopharma.emp.model.UnitGroupSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the UnitGroup service. Represents a row in the &quot;eco_em_portlet_UnitGroup&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.com.ecopharma.emp.model.UnitGroupModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link UnitGroupImpl}.
 * </p>
 *
 * @author tvt
 * @see UnitGroupImpl
 * @see vn.com.ecopharma.emp.model.UnitGroup
 * @see vn.com.ecopharma.emp.model.UnitGroupModel
 * @generated
 */
@JSON(strict = true)
public class UnitGroupModelImpl extends BaseModelImpl<UnitGroup>
	implements UnitGroupModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a unit group model instance should use the {@link vn.com.ecopharma.emp.model.UnitGroup} interface instead.
	 */
	public static final String TABLE_NAME = "eco_em_portlet_UnitGroup";
	public static final Object[][] TABLE_COLUMNS = {
			{ "unitGroupId", Types.BIGINT },
			{ "name", Types.VARCHAR },
			{ "unitId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table eco_em_portlet_UnitGroup (unitGroupId LONG not null primary key,name VARCHAR(75) null,unitId LONG,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table eco_em_portlet_UnitGroup";
	public static final String ORDER_BY_JPQL = " ORDER BY unitGroup.unitGroupId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY eco_em_portlet_UnitGroup.unitGroupId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.com.ecopharma.emp.model.UnitGroup"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.com.ecopharma.emp.model.UnitGroup"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.vn.com.ecopharma.emp.model.UnitGroup"),
			true);
	public static long NAME_COLUMN_BITMASK = 1L;
	public static long UNITID_COLUMN_BITMASK = 2L;
	public static long UNITGROUPID_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static UnitGroup toModel(UnitGroupSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		UnitGroup model = new UnitGroupImpl();

		model.setUnitGroupId(soapModel.getUnitGroupId());
		model.setName(soapModel.getName());
		model.setUnitId(soapModel.getUnitId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<UnitGroup> toModels(UnitGroupSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<UnitGroup> models = new ArrayList<UnitGroup>(soapModels.length);

		for (UnitGroupSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.com.ecopharma.emp.model.UnitGroup"));

	public UnitGroupModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _unitGroupId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setUnitGroupId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _unitGroupId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return UnitGroup.class;
	}

	@Override
	public String getModelClassName() {
		return UnitGroup.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("unitGroupId", getUnitGroupId());
		attributes.put("name", getName());
		attributes.put("unitId", getUnitId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long unitGroupId = (Long)attributes.get("unitGroupId");

		if (unitGroupId != null) {
			setUnitGroupId(unitGroupId);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		Long unitId = (Long)attributes.get("unitId");

		if (unitId != null) {
			setUnitId(unitId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}
	}

	@JSON
	@Override
	public long getUnitGroupId() {
		return _unitGroupId;
	}

	@Override
	public void setUnitGroupId(long unitGroupId) {
		_unitGroupId = unitGroupId;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_columnBitmask |= NAME_COLUMN_BITMASK;

		if (_originalName == null) {
			_originalName = _name;
		}

		_name = name;
	}

	public String getOriginalName() {
		return GetterUtil.getString(_originalName);
	}

	@JSON
	@Override
	public long getUnitId() {
		return _unitId;
	}

	@Override
	public void setUnitId(long unitId) {
		_columnBitmask |= UNITID_COLUMN_BITMASK;

		if (!_setOriginalUnitId) {
			_setOriginalUnitId = true;

			_originalUnitId = _unitId;
		}

		_unitId = unitId;
	}

	public long getOriginalUnitId() {
		return _originalUnitId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			UnitGroup.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public UnitGroup toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (UnitGroup)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		UnitGroupImpl unitGroupImpl = new UnitGroupImpl();

		unitGroupImpl.setUnitGroupId(getUnitGroupId());
		unitGroupImpl.setName(getName());
		unitGroupImpl.setUnitId(getUnitId());
		unitGroupImpl.setGroupId(getGroupId());
		unitGroupImpl.setCompanyId(getCompanyId());
		unitGroupImpl.setUserId(getUserId());
		unitGroupImpl.setUserName(getUserName());
		unitGroupImpl.setCreateDate(getCreateDate());
		unitGroupImpl.setModifiedDate(getModifiedDate());

		unitGroupImpl.resetOriginalValues();

		return unitGroupImpl;
	}

	@Override
	public int compareTo(UnitGroup unitGroup) {
		long primaryKey = unitGroup.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof UnitGroup)) {
			return false;
		}

		UnitGroup unitGroup = (UnitGroup)obj;

		long primaryKey = unitGroup.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		UnitGroupModelImpl unitGroupModelImpl = this;

		unitGroupModelImpl._originalName = unitGroupModelImpl._name;

		unitGroupModelImpl._originalUnitId = unitGroupModelImpl._unitId;

		unitGroupModelImpl._setOriginalUnitId = false;

		unitGroupModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<UnitGroup> toCacheModel() {
		UnitGroupCacheModel unitGroupCacheModel = new UnitGroupCacheModel();

		unitGroupCacheModel.unitGroupId = getUnitGroupId();

		unitGroupCacheModel.name = getName();

		String name = unitGroupCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			unitGroupCacheModel.name = null;
		}

		unitGroupCacheModel.unitId = getUnitId();

		unitGroupCacheModel.groupId = getGroupId();

		unitGroupCacheModel.companyId = getCompanyId();

		unitGroupCacheModel.userId = getUserId();

		unitGroupCacheModel.userName = getUserName();

		String userName = unitGroupCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			unitGroupCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			unitGroupCacheModel.createDate = createDate.getTime();
		}
		else {
			unitGroupCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			unitGroupCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			unitGroupCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return unitGroupCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{unitGroupId=");
		sb.append(getUnitGroupId());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", unitId=");
		sb.append(getUnitId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("vn.com.ecopharma.emp.model.UnitGroup");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>unitGroupId</column-name><column-value><![CDATA[");
		sb.append(getUnitGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>unitId</column-name><column-value><![CDATA[");
		sb.append(getUnitId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = UnitGroup.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			UnitGroup.class
		};
	private long _unitGroupId;
	private String _name;
	private String _originalName;
	private long _unitId;
	private long _originalUnitId;
	private boolean _setOriginalUnitId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private long _columnBitmask;
	private UnitGroup _escapedModel;
}