/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.com.ecopharma.hrm.rc.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CandidateEvaluation service. Represents a row in the &quot;eco_rcp_CandidateEvaluation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.com.ecopharma.hrm.rc.model.impl.CandidateEvaluationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.com.ecopharma.hrm.rc.model.impl.CandidateEvaluationImpl}.
 * </p>
 *
 * @author tvt
 * @see CandidateEvaluation
 * @see vn.com.ecopharma.hrm.rc.model.impl.CandidateEvaluationImpl
 * @see vn.com.ecopharma.hrm.rc.model.impl.CandidateEvaluationModelImpl
 * @generated
 */
public interface CandidateEvaluationModel extends BaseModel<CandidateEvaluation>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a candidate evaluation model instance should use the {@link CandidateEvaluation} interface instead.
	 */

	/**
	 * Returns the primary key of this candidate evaluation.
	 *
	 * @return the primary key of this candidate evaluation
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this candidate evaluation.
	 *
	 * @param primaryKey the primary key of this candidate evaluation
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the candidate evaluation ID of this candidate evaluation.
	 *
	 * @return the candidate evaluation ID of this candidate evaluation
	 */
	public long getCandidateEvaluationId();

	/**
	 * Sets the candidate evaluation ID of this candidate evaluation.
	 *
	 * @param candidateEvaluationId the candidate evaluation ID of this candidate evaluation
	 */
	public void setCandidateEvaluationId(long candidateEvaluationId);

	/**
	 * Returns the evaluation criteria ID of this candidate evaluation.
	 *
	 * @return the evaluation criteria ID of this candidate evaluation
	 */
	public long getEvaluationCriteriaId();

	/**
	 * Sets the evaluation criteria ID of this candidate evaluation.
	 *
	 * @param evaluationCriteriaId the evaluation criteria ID of this candidate evaluation
	 */
	public void setEvaluationCriteriaId(long evaluationCriteriaId);

	/**
	 * Returns the evaluation criteria key value ID of this candidate evaluation.
	 *
	 * @return the evaluation criteria key value ID of this candidate evaluation
	 */
	public long getEvaluationCriteriaKeyValueId();

	/**
	 * Sets the evaluation criteria key value ID of this candidate evaluation.
	 *
	 * @param evaluationCriteriaKeyValueId the evaluation criteria key value ID of this candidate evaluation
	 */
	public void setEvaluationCriteriaKeyValueId(
		long evaluationCriteriaKeyValueId);

	/**
	 * Returns the rating point of this candidate evaluation.
	 *
	 * @return the rating point of this candidate evaluation
	 */
	public int getRatingPoint();

	/**
	 * Sets the rating point of this candidate evaluation.
	 *
	 * @param ratingPoint the rating point of this candidate evaluation
	 */
	public void setRatingPoint(int ratingPoint);

	/**
	 * Returns the note of this candidate evaluation.
	 *
	 * @return the note of this candidate evaluation
	 */
	@AutoEscape
	public String getNote();

	/**
	 * Sets the note of this candidate evaluation.
	 *
	 * @param note the note of this candidate evaluation
	 */
	public void setNote(String note);

	/**
	 * Returns the group ID of this candidate evaluation.
	 *
	 * @return the group ID of this candidate evaluation
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this candidate evaluation.
	 *
	 * @param groupId the group ID of this candidate evaluation
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this candidate evaluation.
	 *
	 * @return the company ID of this candidate evaluation
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this candidate evaluation.
	 *
	 * @param companyId the company ID of this candidate evaluation
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this candidate evaluation.
	 *
	 * @return the user ID of this candidate evaluation
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this candidate evaluation.
	 *
	 * @param userId the user ID of this candidate evaluation
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this candidate evaluation.
	 *
	 * @return the user uuid of this candidate evaluation
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this candidate evaluation.
	 *
	 * @param userUuid the user uuid of this candidate evaluation
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this candidate evaluation.
	 *
	 * @return the user name of this candidate evaluation
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this candidate evaluation.
	 *
	 * @param userName the user name of this candidate evaluation
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this candidate evaluation.
	 *
	 * @return the create date of this candidate evaluation
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this candidate evaluation.
	 *
	 * @param createDate the create date of this candidate evaluation
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this candidate evaluation.
	 *
	 * @return the modified date of this candidate evaluation
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this candidate evaluation.
	 *
	 * @param modifiedDate the modified date of this candidate evaluation
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the candidate ID of this candidate evaluation.
	 *
	 * @return the candidate ID of this candidate evaluation
	 */
	public long getCandidateId();

	/**
	 * Sets the candidate ID of this candidate evaluation.
	 *
	 * @param candidateId the candidate ID of this candidate evaluation
	 */
	public void setCandidateId(long candidateId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(CandidateEvaluation candidateEvaluation);

	@Override
	public int hashCode();

	@Override
	public CacheModel<CandidateEvaluation> toCacheModel();

	@Override
	public CandidateEvaluation toEscapedModel();

	@Override
	public CandidateEvaluation toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}