/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.com.ecopharma.hrm.rc.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Certificate service. Represents a row in the &quot;eco_rcp_Certificate&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.com.ecopharma.hrm.rc.model.impl.CertificateModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.com.ecopharma.hrm.rc.model.impl.CertificateImpl}.
 * </p>
 *
 * @author tvt
 * @see Certificate
 * @see vn.com.ecopharma.hrm.rc.model.impl.CertificateImpl
 * @see vn.com.ecopharma.hrm.rc.model.impl.CertificateModelImpl
 * @generated
 */
public interface CertificateModel extends BaseModel<Certificate>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a certificate model instance should use the {@link Certificate} interface instead.
	 */

	/**
	 * Returns the primary key of this certificate.
	 *
	 * @return the primary key of this certificate
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this certificate.
	 *
	 * @param primaryKey the primary key of this certificate
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the certificate ID of this certificate.
	 *
	 * @return the certificate ID of this certificate
	 */
	public long getCertificateId();

	/**
	 * Sets the certificate ID of this certificate.
	 *
	 * @param certificateId the certificate ID of this certificate
	 */
	public void setCertificateId(long certificateId);

	/**
	 * Returns the class name of this certificate.
	 *
	 * @return the class name of this certificate
	 */
	@AutoEscape
	public String getClassName();

	/**
	 * Sets the class name of this certificate.
	 *
	 * @param className the class name of this certificate
	 */
	public void setClassName(String className);

	/**
	 * Returns the class p k of this certificate.
	 *
	 * @return the class p k of this certificate
	 */
	public long getClassPK();

	/**
	 * Sets the class p k of this certificate.
	 *
	 * @param classPK the class p k of this certificate
	 */
	public void setClassPK(long classPK);

	/**
	 * Returns the name of this certificate.
	 *
	 * @return the name of this certificate
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this certificate.
	 *
	 * @param name the name of this certificate
	 */
	public void setName(String name);

	/**
	 * Returns the certificate type of this certificate.
	 *
	 * @return the certificate type of this certificate
	 */
	@AutoEscape
	public String getCertificateType();

	/**
	 * Sets the certificate type of this certificate.
	 *
	 * @param certificateType the certificate type of this certificate
	 */
	public void setCertificateType(String certificateType);

	/**
	 * Returns the university ID of this certificate.
	 *
	 * @return the university ID of this certificate
	 */
	public long getUniversityId();

	/**
	 * Sets the university ID of this certificate.
	 *
	 * @param universityId the university ID of this certificate
	 */
	public void setUniversityId(long universityId);

	/**
	 * Returns the graduation year of this certificate.
	 *
	 * @return the graduation year of this certificate
	 */
	public int getGraduationYear();

	/**
	 * Sets the graduation year of this certificate.
	 *
	 * @param graduationYear the graduation year of this certificate
	 */
	public void setGraduationYear(int graduationYear);

	/**
	 * Returns the grade of this certificate.
	 *
	 * @return the grade of this certificate
	 */
	@AutoEscape
	public String getGrade();

	/**
	 * Sets the grade of this certificate.
	 *
	 * @param grade the grade of this certificate
	 */
	public void setGrade(String grade);

	/**
	 * Returns the group ID of this certificate.
	 *
	 * @return the group ID of this certificate
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this certificate.
	 *
	 * @param groupId the group ID of this certificate
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this certificate.
	 *
	 * @return the company ID of this certificate
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this certificate.
	 *
	 * @param companyId the company ID of this certificate
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this certificate.
	 *
	 * @return the user ID of this certificate
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this certificate.
	 *
	 * @param userId the user ID of this certificate
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this certificate.
	 *
	 * @return the user uuid of this certificate
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this certificate.
	 *
	 * @param userUuid the user uuid of this certificate
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this certificate.
	 *
	 * @return the user name of this certificate
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this certificate.
	 *
	 * @param userName the user name of this certificate
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this certificate.
	 *
	 * @return the create date of this certificate
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this certificate.
	 *
	 * @param createDate the create date of this certificate
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this certificate.
	 *
	 * @return the modified date of this certificate
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this certificate.
	 *
	 * @param modifiedDate the modified date of this certificate
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the course time from of this certificate.
	 *
	 * @return the course time from of this certificate
	 */
	public Date getCourseTimeFrom();

	/**
	 * Sets the course time from of this certificate.
	 *
	 * @param courseTimeFrom the course time from of this certificate
	 */
	public void setCourseTimeFrom(Date courseTimeFrom);

	/**
	 * Returns the course time to of this certificate.
	 *
	 * @return the course time to of this certificate
	 */
	public Date getCourseTimeTo();

	/**
	 * Sets the course time to of this certificate.
	 *
	 * @param courseTimeTo the course time to of this certificate
	 */
	public void setCourseTimeTo(Date courseTimeTo);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Certificate certificate);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Certificate> toCacheModel();

	@Override
	public Certificate toEscapedModel();

	@Override
	public Certificate toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}