/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.com.ecopharma.hrm.rc.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the EvaluationCriteriaKeyValue service. Represents a row in the &quot;eco_rcp_EvaluationCriteriaKeyValue&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.com.ecopharma.hrm.rc.model.impl.EvaluationCriteriaKeyValueModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.com.ecopharma.hrm.rc.model.impl.EvaluationCriteriaKeyValueImpl}.
 * </p>
 *
 * @author tvt
 * @see EvaluationCriteriaKeyValue
 * @see vn.com.ecopharma.hrm.rc.model.impl.EvaluationCriteriaKeyValueImpl
 * @see vn.com.ecopharma.hrm.rc.model.impl.EvaluationCriteriaKeyValueModelImpl
 * @generated
 */
public interface EvaluationCriteriaKeyValueModel extends BaseModel<EvaluationCriteriaKeyValue>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a evaluation criteria key value model instance should use the {@link EvaluationCriteriaKeyValue} interface instead.
	 */

	/**
	 * Returns the primary key of this evaluation criteria key value.
	 *
	 * @return the primary key of this evaluation criteria key value
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this evaluation criteria key value.
	 *
	 * @param primaryKey the primary key of this evaluation criteria key value
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the evaluation criteria key value ID of this evaluation criteria key value.
	 *
	 * @return the evaluation criteria key value ID of this evaluation criteria key value
	 */
	public long getEvaluationCriteriaKeyValueId();

	/**
	 * Sets the evaluation criteria key value ID of this evaluation criteria key value.
	 *
	 * @param evaluationCriteriaKeyValueId the evaluation criteria key value ID of this evaluation criteria key value
	 */
	public void setEvaluationCriteriaKeyValueId(
		long evaluationCriteriaKeyValueId);

	/**
	 * Returns the evaluation criteria ID of this evaluation criteria key value.
	 *
	 * @return the evaluation criteria ID of this evaluation criteria key value
	 */
	public long getEvaluationCriteriaId();

	/**
	 * Sets the evaluation criteria ID of this evaluation criteria key value.
	 *
	 * @param evaluationCriteriaId the evaluation criteria ID of this evaluation criteria key value
	 */
	public void setEvaluationCriteriaId(long evaluationCriteriaId);

	/**
	 * Returns the key of this evaluation criteria key value.
	 *
	 * @return the key of this evaluation criteria key value
	 */
	@AutoEscape
	public String getKey();

	/**
	 * Sets the key of this evaluation criteria key value.
	 *
	 * @param key the key of this evaluation criteria key value
	 */
	public void setKey(String key);

	/**
	 * Returns the value of this evaluation criteria key value.
	 *
	 * @return the value of this evaluation criteria key value
	 */
	public int getValue();

	/**
	 * Sets the value of this evaluation criteria key value.
	 *
	 * @param value the value of this evaluation criteria key value
	 */
	public void setValue(int value);

	/**
	 * Returns the group ID of this evaluation criteria key value.
	 *
	 * @return the group ID of this evaluation criteria key value
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this evaluation criteria key value.
	 *
	 * @param groupId the group ID of this evaluation criteria key value
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this evaluation criteria key value.
	 *
	 * @return the company ID of this evaluation criteria key value
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this evaluation criteria key value.
	 *
	 * @param companyId the company ID of this evaluation criteria key value
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this evaluation criteria key value.
	 *
	 * @return the user ID of this evaluation criteria key value
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this evaluation criteria key value.
	 *
	 * @param userId the user ID of this evaluation criteria key value
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this evaluation criteria key value.
	 *
	 * @return the user uuid of this evaluation criteria key value
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this evaluation criteria key value.
	 *
	 * @param userUuid the user uuid of this evaluation criteria key value
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this evaluation criteria key value.
	 *
	 * @return the user name of this evaluation criteria key value
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this evaluation criteria key value.
	 *
	 * @param userName the user name of this evaluation criteria key value
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this evaluation criteria key value.
	 *
	 * @return the create date of this evaluation criteria key value
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this evaluation criteria key value.
	 *
	 * @param createDate the create date of this evaluation criteria key value
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this evaluation criteria key value.
	 *
	 * @return the modified date of this evaluation criteria key value
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this evaluation criteria key value.
	 *
	 * @param modifiedDate the modified date of this evaluation criteria key value
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(EvaluationCriteriaKeyValue evaluationCriteriaKeyValue);

	@Override
	public int hashCode();

	@Override
	public CacheModel<EvaluationCriteriaKeyValue> toCacheModel();

	@Override
	public EvaluationCriteriaKeyValue toEscapedModel();

	@Override
	public EvaluationCriteriaKeyValue toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}