/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.com.ecopharma.hrm.rc.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Experience service. Represents a row in the &quot;eco_rcp_Experience&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.com.ecopharma.hrm.rc.model.impl.ExperienceModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.com.ecopharma.hrm.rc.model.impl.ExperienceImpl}.
 * </p>
 *
 * @author tvt
 * @see Experience
 * @see vn.com.ecopharma.hrm.rc.model.impl.ExperienceImpl
 * @see vn.com.ecopharma.hrm.rc.model.impl.ExperienceModelImpl
 * @generated
 */
public interface ExperienceModel extends BaseModel<Experience>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a experience model instance should use the {@link Experience} interface instead.
	 */

	/**
	 * Returns the primary key of this experience.
	 *
	 * @return the primary key of this experience
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this experience.
	 *
	 * @param primaryKey the primary key of this experience
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the experience ID of this experience.
	 *
	 * @return the experience ID of this experience
	 */
	public long getExperienceId();

	/**
	 * Sets the experience ID of this experience.
	 *
	 * @param experienceId the experience ID of this experience
	 */
	public void setExperienceId(long experienceId);

	/**
	 * Returns the class name of this experience.
	 *
	 * @return the class name of this experience
	 */
	@AutoEscape
	public String getClassName();

	/**
	 * Sets the class name of this experience.
	 *
	 * @param className the class name of this experience
	 */
	public void setClassName(String className);

	/**
	 * Returns the class p k of this experience.
	 *
	 * @return the class p k of this experience
	 */
	public long getClassPK();

	/**
	 * Sets the class p k of this experience.
	 *
	 * @param classPK the class p k of this experience
	 */
	public void setClassPK(long classPK);

	/**
	 * Returns the company name of this experience.
	 *
	 * @return the company name of this experience
	 */
	@AutoEscape
	public String getCompanyName();

	/**
	 * Sets the company name of this experience.
	 *
	 * @param companyName the company name of this experience
	 */
	public void setCompanyName(String companyName);

	/**
	 * Returns the working place of this experience.
	 *
	 * @return the working place of this experience
	 */
	@AutoEscape
	public String getWorkingPlace();

	/**
	 * Sets the working place of this experience.
	 *
	 * @param workingPlace the working place of this experience
	 */
	public void setWorkingPlace(String workingPlace);

	/**
	 * Returns the years experience of this experience.
	 *
	 * @return the years experience of this experience
	 */
	public double getYearsExperience();

	/**
	 * Sets the years experience of this experience.
	 *
	 * @param yearsExperience the years experience of this experience
	 */
	public void setYearsExperience(double yearsExperience);

	/**
	 * Returns the tel of this experience.
	 *
	 * @return the tel of this experience
	 */
	@AutoEscape
	public String getTel();

	/**
	 * Sets the tel of this experience.
	 *
	 * @param tel the tel of this experience
	 */
	public void setTel(String tel);

	/**
	 * Returns the working from of this experience.
	 *
	 * @return the working from of this experience
	 */
	public Date getWorkingFrom();

	/**
	 * Sets the working from of this experience.
	 *
	 * @param workingFrom the working from of this experience
	 */
	public void setWorkingFrom(Date workingFrom);

	/**
	 * Returns the working to of this experience.
	 *
	 * @return the working to of this experience
	 */
	public Date getWorkingTo();

	/**
	 * Sets the working to of this experience.
	 *
	 * @param workingTo the working to of this experience
	 */
	public void setWorkingTo(Date workingTo);

	/**
	 * Returns the initial titles of this experience.
	 *
	 * @return the initial titles of this experience
	 */
	@AutoEscape
	public String getInitialTitles();

	/**
	 * Sets the initial titles of this experience.
	 *
	 * @param initialTitles the initial titles of this experience
	 */
	public void setInitialTitles(String initialTitles);

	/**
	 * Returns the final titles of this experience.
	 *
	 * @return the final titles of this experience
	 */
	@AutoEscape
	public String getFinalTitles();

	/**
	 * Sets the final titles of this experience.
	 *
	 * @param finalTitles the final titles of this experience
	 */
	public void setFinalTitles(String finalTitles);

	/**
	 * Returns the initial salary of this experience.
	 *
	 * @return the initial salary of this experience
	 */
	public double getInitialSalary();

	/**
	 * Sets the initial salary of this experience.
	 *
	 * @param initialSalary the initial salary of this experience
	 */
	public void setInitialSalary(double initialSalary);

	/**
	 * Returns the final salary of this experience.
	 *
	 * @return the final salary of this experience
	 */
	public double getFinalSalary();

	/**
	 * Sets the final salary of this experience.
	 *
	 * @param finalSalary the final salary of this experience
	 */
	public void setFinalSalary(double finalSalary);

	/**
	 * Returns the field of this experience.
	 *
	 * @return the field of this experience
	 */
	@AutoEscape
	public String getField();

	/**
	 * Sets the field of this experience.
	 *
	 * @param field the field of this experience
	 */
	public void setField(String field);

	/**
	 * Returns the manager of this experience.
	 *
	 * @return the manager of this experience
	 */
	@AutoEscape
	public String getManager();

	/**
	 * Sets the manager of this experience.
	 *
	 * @param manager the manager of this experience
	 */
	public void setManager(String manager);

	/**
	 * Returns the responsibility of this experience.
	 *
	 * @return the responsibility of this experience
	 */
	@AutoEscape
	public String getResponsibility();

	/**
	 * Sets the responsibility of this experience.
	 *
	 * @param responsibility the responsibility of this experience
	 */
	public void setResponsibility(String responsibility);

	/**
	 * Returns the resigned reason of this experience.
	 *
	 * @return the resigned reason of this experience
	 */
	@AutoEscape
	public String getResignedReason();

	/**
	 * Sets the resigned reason of this experience.
	 *
	 * @param resignedReason the resigned reason of this experience
	 */
	public void setResignedReason(String resignedReason);

	/**
	 * Returns the description of this experience.
	 *
	 * @return the description of this experience
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this experience.
	 *
	 * @param description the description of this experience
	 */
	public void setDescription(String description);

	/**
	 * Returns the group ID of this experience.
	 *
	 * @return the group ID of this experience
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this experience.
	 *
	 * @param groupId the group ID of this experience
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this experience.
	 *
	 * @return the company ID of this experience
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this experience.
	 *
	 * @param companyId the company ID of this experience
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this experience.
	 *
	 * @return the user ID of this experience
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this experience.
	 *
	 * @param userId the user ID of this experience
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this experience.
	 *
	 * @return the user uuid of this experience
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this experience.
	 *
	 * @param userUuid the user uuid of this experience
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this experience.
	 *
	 * @return the user name of this experience
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this experience.
	 *
	 * @param userName the user name of this experience
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this experience.
	 *
	 * @return the create date of this experience
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this experience.
	 *
	 * @param createDate the create date of this experience
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this experience.
	 *
	 * @return the modified date of this experience
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this experience.
	 *
	 * @param modifiedDate the modified date of this experience
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Experience experience);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Experience> toCacheModel();

	@Override
	public Experience toEscapedModel();

	@Override
	public Experience toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}