/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.com.ecopharma.hrm.rc.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Skill service. Represents a row in the &quot;eco_rcp_Skill&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.com.ecopharma.hrm.rc.model.impl.SkillModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.com.ecopharma.hrm.rc.model.impl.SkillImpl}.
 * </p>
 *
 * @author tvt
 * @see Skill
 * @see vn.com.ecopharma.hrm.rc.model.impl.SkillImpl
 * @see vn.com.ecopharma.hrm.rc.model.impl.SkillModelImpl
 * @generated
 */
public interface SkillModel extends BaseModel<Skill>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a skill model instance should use the {@link Skill} interface instead.
	 */

	/**
	 * Returns the primary key of this skill.
	 *
	 * @return the primary key of this skill
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this skill.
	 *
	 * @param primaryKey the primary key of this skill
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the skill ID of this skill.
	 *
	 * @return the skill ID of this skill
	 */
	public long getSkillId();

	/**
	 * Sets the skill ID of this skill.
	 *
	 * @param skillId the skill ID of this skill
	 */
	public void setSkillId(long skillId);

	/**
	 * Returns the candidate ID of this skill.
	 *
	 * @return the candidate ID of this skill
	 */
	public long getCandidateId();

	/**
	 * Sets the candidate ID of this skill.
	 *
	 * @param candidateId the candidate ID of this skill
	 */
	public void setCandidateId(long candidateId);

	/**
	 * Returns the grade of this skill.
	 *
	 * @return the grade of this skill
	 */
	@AutoEscape
	public String getGrade();

	/**
	 * Sets the grade of this skill.
	 *
	 * @param grade the grade of this skill
	 */
	public void setGrade(String grade);

	/**
	 * Returns the type of this skill.
	 *
	 * @return the type of this skill
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this skill.
	 *
	 * @param type the type of this skill
	 */
	public void setType(String type);

	/**
	 * Returns the group ID of this skill.
	 *
	 * @return the group ID of this skill
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this skill.
	 *
	 * @param groupId the group ID of this skill
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this skill.
	 *
	 * @return the company ID of this skill
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this skill.
	 *
	 * @param companyId the company ID of this skill
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this skill.
	 *
	 * @return the user ID of this skill
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this skill.
	 *
	 * @param userId the user ID of this skill
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this skill.
	 *
	 * @return the user uuid of this skill
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this skill.
	 *
	 * @param userUuid the user uuid of this skill
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this skill.
	 *
	 * @return the user name of this skill
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this skill.
	 *
	 * @param userName the user name of this skill
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this skill.
	 *
	 * @return the create date of this skill
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this skill.
	 *
	 * @param createDate the create date of this skill
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this skill.
	 *
	 * @return the modified date of this skill
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this skill.
	 *
	 * @param modifiedDate the modified date of this skill
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Skill skill);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Skill> toCacheModel();

	@Override
	public Skill toEscapedModel();

	@Override
	public Skill toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}