/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.com.ecopharma.hrm.rc.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VacancyCandidate service. Represents a row in the &quot;eco_rcp_VacancyCandidate&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.com.ecopharma.hrm.rc.model.impl.VacancyCandidateModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.com.ecopharma.hrm.rc.model.impl.VacancyCandidateImpl}.
 * </p>
 *
 * @author tvt
 * @see VacancyCandidate
 * @see vn.com.ecopharma.hrm.rc.model.impl.VacancyCandidateImpl
 * @see vn.com.ecopharma.hrm.rc.model.impl.VacancyCandidateModelImpl
 * @generated
 */
public interface VacancyCandidateModel extends BaseModel<VacancyCandidate>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vacancy candidate model instance should use the {@link VacancyCandidate} interface instead.
	 */

	/**
	 * Returns the primary key of this vacancy candidate.
	 *
	 * @return the primary key of this vacancy candidate
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this vacancy candidate.
	 *
	 * @param primaryKey the primary key of this vacancy candidate
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the vacancy candidate ID of this vacancy candidate.
	 *
	 * @return the vacancy candidate ID of this vacancy candidate
	 */
	public long getVacancyCandidateId();

	/**
	 * Sets the vacancy candidate ID of this vacancy candidate.
	 *
	 * @param vacancyCandidateId the vacancy candidate ID of this vacancy candidate
	 */
	public void setVacancyCandidateId(long vacancyCandidateId);

	/**
	 * Returns the vacancy ID of this vacancy candidate.
	 *
	 * @return the vacancy ID of this vacancy candidate
	 */
	public long getVacancyId();

	/**
	 * Sets the vacancy ID of this vacancy candidate.
	 *
	 * @param vacancyId the vacancy ID of this vacancy candidate
	 */
	public void setVacancyId(long vacancyId);

	/**
	 * Returns the candidate ID of this vacancy candidate.
	 *
	 * @return the candidate ID of this vacancy candidate
	 */
	public long getCandidateId();

	/**
	 * Sets the candidate ID of this vacancy candidate.
	 *
	 * @param candidateId the candidate ID of this vacancy candidate
	 */
	public void setCandidateId(long candidateId);

	/**
	 * Returns the status of this vacancy candidate.
	 *
	 * @return the status of this vacancy candidate
	 */
	public int getStatus();

	/**
	 * Sets the status of this vacancy candidate.
	 *
	 * @param status the status of this vacancy candidate
	 */
	public void setStatus(int status);

	/**
	 * Returns the group ID of this vacancy candidate.
	 *
	 * @return the group ID of this vacancy candidate
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this vacancy candidate.
	 *
	 * @param groupId the group ID of this vacancy candidate
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this vacancy candidate.
	 *
	 * @return the company ID of this vacancy candidate
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this vacancy candidate.
	 *
	 * @param companyId the company ID of this vacancy candidate
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this vacancy candidate.
	 *
	 * @return the user ID of this vacancy candidate
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this vacancy candidate.
	 *
	 * @param userId the user ID of this vacancy candidate
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this vacancy candidate.
	 *
	 * @return the user uuid of this vacancy candidate
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this vacancy candidate.
	 *
	 * @param userUuid the user uuid of this vacancy candidate
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this vacancy candidate.
	 *
	 * @return the user name of this vacancy candidate
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this vacancy candidate.
	 *
	 * @param userName the user name of this vacancy candidate
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this vacancy candidate.
	 *
	 * @return the create date of this vacancy candidate
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this vacancy candidate.
	 *
	 * @param createDate the create date of this vacancy candidate
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this vacancy candidate.
	 *
	 * @return the modified date of this vacancy candidate
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this vacancy candidate.
	 *
	 * @param modifiedDate the modified date of this vacancy candidate
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the type of this vacancy candidate.
	 *
	 * @return the type of this vacancy candidate
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this vacancy candidate.
	 *
	 * @param type the type of this vacancy candidate
	 */
	public void setType(String type);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(VacancyCandidate vacancyCandidate);

	@Override
	public int hashCode();

	@Override
	public CacheModel<VacancyCandidate> toCacheModel();

	@Override
	public VacancyCandidate toEscapedModel();

	@Override
	public VacancyCandidate toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}