/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.com.ecopharma.hrm.rc.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VacancyEvaluationCriteria service. Represents a row in the &quot;eco_rcp_VacancyEvaluationCriteria&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.com.ecopharma.hrm.rc.model.impl.VacancyEvaluationCriteriaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.com.ecopharma.hrm.rc.model.impl.VacancyEvaluationCriteriaImpl}.
 * </p>
 *
 * @author tvt
 * @see VacancyEvaluationCriteria
 * @see vn.com.ecopharma.hrm.rc.model.impl.VacancyEvaluationCriteriaImpl
 * @see vn.com.ecopharma.hrm.rc.model.impl.VacancyEvaluationCriteriaModelImpl
 * @generated
 */
public interface VacancyEvaluationCriteriaModel extends BaseModel<VacancyEvaluationCriteria>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vacancy evaluation criteria model instance should use the {@link VacancyEvaluationCriteria} interface instead.
	 */

	/**
	 * Returns the primary key of this vacancy evaluation criteria.
	 *
	 * @return the primary key of this vacancy evaluation criteria
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this vacancy evaluation criteria.
	 *
	 * @param primaryKey the primary key of this vacancy evaluation criteria
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the vacancy evaluation criteria ID of this vacancy evaluation criteria.
	 *
	 * @return the vacancy evaluation criteria ID of this vacancy evaluation criteria
	 */
	public long getVacancyEvaluationCriteriaId();

	/**
	 * Sets the vacancy evaluation criteria ID of this vacancy evaluation criteria.
	 *
	 * @param vacancyEvaluationCriteriaId the vacancy evaluation criteria ID of this vacancy evaluation criteria
	 */
	public void setVacancyEvaluationCriteriaId(long vacancyEvaluationCriteriaId);

	/**
	 * Returns the vacancy ID of this vacancy evaluation criteria.
	 *
	 * @return the vacancy ID of this vacancy evaluation criteria
	 */
	public long getVacancyId();

	/**
	 * Sets the vacancy ID of this vacancy evaluation criteria.
	 *
	 * @param vacancyId the vacancy ID of this vacancy evaluation criteria
	 */
	public void setVacancyId(long vacancyId);

	/**
	 * Returns the evaluation criteria ID of this vacancy evaluation criteria.
	 *
	 * @return the evaluation criteria ID of this vacancy evaluation criteria
	 */
	public long getEvaluationCriteriaId();

	/**
	 * Sets the evaluation criteria ID of this vacancy evaluation criteria.
	 *
	 * @param evaluationCriteriaId the evaluation criteria ID of this vacancy evaluation criteria
	 */
	public void setEvaluationCriteriaId(long evaluationCriteriaId);

	/**
	 * Returns the group ID of this vacancy evaluation criteria.
	 *
	 * @return the group ID of this vacancy evaluation criteria
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this vacancy evaluation criteria.
	 *
	 * @param groupId the group ID of this vacancy evaluation criteria
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this vacancy evaluation criteria.
	 *
	 * @return the company ID of this vacancy evaluation criteria
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this vacancy evaluation criteria.
	 *
	 * @param companyId the company ID of this vacancy evaluation criteria
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this vacancy evaluation criteria.
	 *
	 * @return the user ID of this vacancy evaluation criteria
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this vacancy evaluation criteria.
	 *
	 * @param userId the user ID of this vacancy evaluation criteria
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this vacancy evaluation criteria.
	 *
	 * @return the user uuid of this vacancy evaluation criteria
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this vacancy evaluation criteria.
	 *
	 * @param userUuid the user uuid of this vacancy evaluation criteria
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this vacancy evaluation criteria.
	 *
	 * @return the user name of this vacancy evaluation criteria
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this vacancy evaluation criteria.
	 *
	 * @param userName the user name of this vacancy evaluation criteria
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this vacancy evaluation criteria.
	 *
	 * @return the create date of this vacancy evaluation criteria
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this vacancy evaluation criteria.
	 *
	 * @param createDate the create date of this vacancy evaluation criteria
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this vacancy evaluation criteria.
	 *
	 * @return the modified date of this vacancy evaluation criteria
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this vacancy evaluation criteria.
	 *
	 * @param modifiedDate the modified date of this vacancy evaluation criteria
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(VacancyEvaluationCriteria vacancyEvaluationCriteria);

	@Override
	public int hashCode();

	@Override
	public CacheModel<VacancyEvaluationCriteria> toCacheModel();

	@Override
	public VacancyEvaluationCriteria toEscapedModel();

	@Override
	public VacancyEvaluationCriteria toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}