/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.com.ecopharma.hrm.rc.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Vacancy service. Represents a row in the &quot;eco_rcp_Vacancy&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.com.ecopharma.hrm.rc.model.impl.VacancyModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.com.ecopharma.hrm.rc.model.impl.VacancyImpl}.
 * </p>
 *
 * @author tvt
 * @see Vacancy
 * @see vn.com.ecopharma.hrm.rc.model.impl.VacancyImpl
 * @see vn.com.ecopharma.hrm.rc.model.impl.VacancyModelImpl
 * @generated
 */
public interface VacancyModel extends BaseModel<Vacancy>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vacancy model instance should use the {@link Vacancy} interface instead.
	 */

	/**
	 * Returns the primary key of this vacancy.
	 *
	 * @return the primary key of this vacancy
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this vacancy.
	 *
	 * @param primaryKey the primary key of this vacancy
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the vacancy ID of this vacancy.
	 *
	 * @return the vacancy ID of this vacancy
	 */
	public long getVacancyId();

	/**
	 * Sets the vacancy ID of this vacancy.
	 *
	 * @param vacancyId the vacancy ID of this vacancy
	 */
	public void setVacancyId(long vacancyId);

	/**
	 * Returns the name of this vacancy.
	 *
	 * @return the name of this vacancy
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this vacancy.
	 *
	 * @param name the name of this vacancy
	 */
	public void setName(String name);

	/**
	 * Returns the number of position of this vacancy.
	 *
	 * @return the number of position of this vacancy
	 */
	public int getNumberOfPosition();

	/**
	 * Sets the number of position of this vacancy.
	 *
	 * @param numberOfPosition the number of position of this vacancy
	 */
	public void setNumberOfPosition(int numberOfPosition);

	/**
	 * Returns the titles ID of this vacancy.
	 *
	 * @return the titles ID of this vacancy
	 */
	public long getTitlesId();

	/**
	 * Sets the titles ID of this vacancy.
	 *
	 * @param titlesId the titles ID of this vacancy
	 */
	public void setTitlesId(long titlesId);

	/**
	 * Returns the status of this vacancy.
	 *
	 * @return the status of this vacancy
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this vacancy.
	 *
	 * @param status the status of this vacancy
	 */
	public void setStatus(String status);

	/**
	 * Returns the posted date of this vacancy.
	 *
	 * @return the posted date of this vacancy
	 */
	public Date getPostedDate();

	/**
	 * Sets the posted date of this vacancy.
	 *
	 * @param postedDate the posted date of this vacancy
	 */
	public void setPostedDate(Date postedDate);

	/**
	 * Returns the expired date of this vacancy.
	 *
	 * @return the expired date of this vacancy
	 */
	public Date getExpiredDate();

	/**
	 * Sets the expired date of this vacancy.
	 *
	 * @param expiredDate the expired date of this vacancy
	 */
	public void setExpiredDate(Date expiredDate);

	/**
	 * Returns the deleted of this vacancy.
	 *
	 * @return the deleted of this vacancy
	 */
	public boolean getDeleted();

	/**
	 * Returns <code>true</code> if this vacancy is deleted.
	 *
	 * @return <code>true</code> if this vacancy is deleted; <code>false</code> otherwise
	 */
	public boolean isDeleted();

	/**
	 * Sets whether this vacancy is deleted.
	 *
	 * @param deleted the deleted of this vacancy
	 */
	public void setDeleted(boolean deleted);

	/**
	 * Returns the description of this vacancy.
	 *
	 * @return the description of this vacancy
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this vacancy.
	 *
	 * @param description the description of this vacancy
	 */
	public void setDescription(String description);

	/**
	 * Returns the group ID of this vacancy.
	 *
	 * @return the group ID of this vacancy
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this vacancy.
	 *
	 * @param groupId the group ID of this vacancy
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this vacancy.
	 *
	 * @return the company ID of this vacancy
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this vacancy.
	 *
	 * @param companyId the company ID of this vacancy
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this vacancy.
	 *
	 * @return the user ID of this vacancy
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this vacancy.
	 *
	 * @param userId the user ID of this vacancy
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this vacancy.
	 *
	 * @return the user uuid of this vacancy
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this vacancy.
	 *
	 * @param userUuid the user uuid of this vacancy
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this vacancy.
	 *
	 * @return the user name of this vacancy
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this vacancy.
	 *
	 * @param userName the user name of this vacancy
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this vacancy.
	 *
	 * @return the create date of this vacancy
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this vacancy.
	 *
	 * @param createDate the create date of this vacancy
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this vacancy.
	 *
	 * @return the modified date of this vacancy
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this vacancy.
	 *
	 * @param modifiedDate the modified date of this vacancy
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the code of this vacancy.
	 *
	 * @return the code of this vacancy
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this vacancy.
	 *
	 * @param code the code of this vacancy
	 */
	public void setCode(String code);

	/**
	 * Returns the certificate type of this vacancy.
	 *
	 * @return the certificate type of this vacancy
	 */
	@AutoEscape
	public String getCertificateType();

	/**
	 * Sets the certificate type of this vacancy.
	 *
	 * @param certificateType the certificate type of this vacancy
	 */
	public void setCertificateType(String certificateType);

	/**
	 * Returns the experiences of this vacancy.
	 *
	 * @return the experiences of this vacancy
	 */
	public double getExperiences();

	/**
	 * Sets the experiences of this vacancy.
	 *
	 * @param experiences the experiences of this vacancy
	 */
	public void setExperiences(double experiences);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Vacancy vacancy);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Vacancy> toCacheModel();

	@Override
	public Vacancy toEscapedModel();

	@Override
	public Vacancy toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}