/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.com.ecopharma.hrm.rc.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import vn.com.ecopharma.hrm.rc.model.Certificate;
import vn.com.ecopharma.hrm.rc.model.CertificateModel;
import vn.com.ecopharma.hrm.rc.model.CertificateSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Certificate service. Represents a row in the &quot;eco_rcp_Certificate&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.com.ecopharma.hrm.rc.model.CertificateModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CertificateImpl}.
 * </p>
 *
 * @author tvt
 * @see CertificateImpl
 * @see vn.com.ecopharma.hrm.rc.model.Certificate
 * @see vn.com.ecopharma.hrm.rc.model.CertificateModel
 * @generated
 */
@JSON(strict = true)
public class CertificateModelImpl extends BaseModelImpl<Certificate>
	implements CertificateModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a certificate model instance should use the {@link vn.com.ecopharma.hrm.rc.model.Certificate} interface instead.
	 */
	public static final String TABLE_NAME = "eco_rcp_Certificate";
	public static final Object[][] TABLE_COLUMNS = {
			{ "certificateId", Types.BIGINT },
			{ "className", Types.VARCHAR },
			{ "classPK", Types.BIGINT },
			{ "name", Types.VARCHAR },
			{ "certificateType", Types.VARCHAR },
			{ "universityId", Types.BIGINT },
			{ "graduationYear", Types.INTEGER },
			{ "grade", Types.VARCHAR },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "courseTimeFrom", Types.TIMESTAMP },
			{ "courseTimeTo", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table eco_rcp_Certificate (certificateId LONG not null primary key,className VARCHAR(75) null,classPK LONG,name VARCHAR(75) null,certificateType VARCHAR(75) null,universityId LONG,graduationYear INTEGER,grade VARCHAR(75) null,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,courseTimeFrom DATE null,courseTimeTo DATE null)";
	public static final String TABLE_SQL_DROP = "drop table eco_rcp_Certificate";
	public static final String ORDER_BY_JPQL = " ORDER BY certificate.certificateId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY eco_rcp_Certificate.certificateId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.com.ecopharma.hrm.rc.model.Certificate"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.com.ecopharma.hrm.rc.model.Certificate"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.vn.com.ecopharma.hrm.rc.model.Certificate"),
			true);
	public static long CLASSNAME_COLUMN_BITMASK = 1L;
	public static long CLASSPK_COLUMN_BITMASK = 2L;
	public static long CERTIFICATEID_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Certificate toModel(CertificateSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Certificate model = new CertificateImpl();

		model.setCertificateId(soapModel.getCertificateId());
		model.setClassName(soapModel.getClassName());
		model.setClassPK(soapModel.getClassPK());
		model.setName(soapModel.getName());
		model.setCertificateType(soapModel.getCertificateType());
		model.setUniversityId(soapModel.getUniversityId());
		model.setGraduationYear(soapModel.getGraduationYear());
		model.setGrade(soapModel.getGrade());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setCourseTimeFrom(soapModel.getCourseTimeFrom());
		model.setCourseTimeTo(soapModel.getCourseTimeTo());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Certificate> toModels(CertificateSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Certificate> models = new ArrayList<Certificate>(soapModels.length);

		for (CertificateSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.com.ecopharma.hrm.rc.model.Certificate"));

	public CertificateModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _certificateId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCertificateId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _certificateId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Certificate.class;
	}

	@Override
	public String getModelClassName() {
		return Certificate.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("certificateId", getCertificateId());
		attributes.put("className", getClassName());
		attributes.put("classPK", getClassPK());
		attributes.put("name", getName());
		attributes.put("certificateType", getCertificateType());
		attributes.put("universityId", getUniversityId());
		attributes.put("graduationYear", getGraduationYear());
		attributes.put("grade", getGrade());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("courseTimeFrom", getCourseTimeFrom());
		attributes.put("courseTimeTo", getCourseTimeTo());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long certificateId = (Long)attributes.get("certificateId");

		if (certificateId != null) {
			setCertificateId(certificateId);
		}

		String className = (String)attributes.get("className");

		if (className != null) {
			setClassName(className);
		}

		Long classPK = (Long)attributes.get("classPK");

		if (classPK != null) {
			setClassPK(classPK);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		String certificateType = (String)attributes.get("certificateType");

		if (certificateType != null) {
			setCertificateType(certificateType);
		}

		Long universityId = (Long)attributes.get("universityId");

		if (universityId != null) {
			setUniversityId(universityId);
		}

		Integer graduationYear = (Integer)attributes.get("graduationYear");

		if (graduationYear != null) {
			setGraduationYear(graduationYear);
		}

		String grade = (String)attributes.get("grade");

		if (grade != null) {
			setGrade(grade);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Date courseTimeFrom = (Date)attributes.get("courseTimeFrom");

		if (courseTimeFrom != null) {
			setCourseTimeFrom(courseTimeFrom);
		}

		Date courseTimeTo = (Date)attributes.get("courseTimeTo");

		if (courseTimeTo != null) {
			setCourseTimeTo(courseTimeTo);
		}
	}

	@JSON
	@Override
	public long getCertificateId() {
		return _certificateId;
	}

	@Override
	public void setCertificateId(long certificateId) {
		_certificateId = certificateId;
	}

	@JSON
	@Override
	public String getClassName() {
		if (_className == null) {
			return StringPool.BLANK;
		}
		else {
			return _className;
		}
	}

	@Override
	public void setClassName(String className) {
		_columnBitmask |= CLASSNAME_COLUMN_BITMASK;

		if (_originalClassName == null) {
			_originalClassName = _className;
		}

		_className = className;
	}

	public String getOriginalClassName() {
		return GetterUtil.getString(_originalClassName);
	}

	@JSON
	@Override
	public long getClassPK() {
		return _classPK;
	}

	@Override
	public void setClassPK(long classPK) {
		_columnBitmask |= CLASSPK_COLUMN_BITMASK;

		if (!_setOriginalClassPK) {
			_setOriginalClassPK = true;

			_originalClassPK = _classPK;
		}

		_classPK = classPK;
	}

	public long getOriginalClassPK() {
		return _originalClassPK;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@JSON
	@Override
	public String getCertificateType() {
		if (_certificateType == null) {
			return StringPool.BLANK;
		}
		else {
			return _certificateType;
		}
	}

	@Override
	public void setCertificateType(String certificateType) {
		_certificateType = certificateType;
	}

	@JSON
	@Override
	public long getUniversityId() {
		return _universityId;
	}

	@Override
	public void setUniversityId(long universityId) {
		_universityId = universityId;
	}

	@JSON
	@Override
	public int getGraduationYear() {
		return _graduationYear;
	}

	@Override
	public void setGraduationYear(int graduationYear) {
		_graduationYear = graduationYear;
	}

	@JSON
	@Override
	public String getGrade() {
		if (_grade == null) {
			return StringPool.BLANK;
		}
		else {
			return _grade;
		}
	}

	@Override
	public void setGrade(String grade) {
		_grade = grade;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public Date getCourseTimeFrom() {
		return _courseTimeFrom;
	}

	@Override
	public void setCourseTimeFrom(Date courseTimeFrom) {
		_courseTimeFrom = courseTimeFrom;
	}

	@JSON
	@Override
	public Date getCourseTimeTo() {
		return _courseTimeTo;
	}

	@Override
	public void setCourseTimeTo(Date courseTimeTo) {
		_courseTimeTo = courseTimeTo;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			Certificate.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Certificate toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Certificate)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CertificateImpl certificateImpl = new CertificateImpl();

		certificateImpl.setCertificateId(getCertificateId());
		certificateImpl.setClassName(getClassName());
		certificateImpl.setClassPK(getClassPK());
		certificateImpl.setName(getName());
		certificateImpl.setCertificateType(getCertificateType());
		certificateImpl.setUniversityId(getUniversityId());
		certificateImpl.setGraduationYear(getGraduationYear());
		certificateImpl.setGrade(getGrade());
		certificateImpl.setGroupId(getGroupId());
		certificateImpl.setCompanyId(getCompanyId());
		certificateImpl.setUserId(getUserId());
		certificateImpl.setUserName(getUserName());
		certificateImpl.setCreateDate(getCreateDate());
		certificateImpl.setModifiedDate(getModifiedDate());
		certificateImpl.setCourseTimeFrom(getCourseTimeFrom());
		certificateImpl.setCourseTimeTo(getCourseTimeTo());

		certificateImpl.resetOriginalValues();

		return certificateImpl;
	}

	@Override
	public int compareTo(Certificate certificate) {
		long primaryKey = certificate.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Certificate)) {
			return false;
		}

		Certificate certificate = (Certificate)obj;

		long primaryKey = certificate.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		CertificateModelImpl certificateModelImpl = this;

		certificateModelImpl._originalClassName = certificateModelImpl._className;

		certificateModelImpl._originalClassPK = certificateModelImpl._classPK;

		certificateModelImpl._setOriginalClassPK = false;

		certificateModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Certificate> toCacheModel() {
		CertificateCacheModel certificateCacheModel = new CertificateCacheModel();

		certificateCacheModel.certificateId = getCertificateId();

		certificateCacheModel.className = getClassName();

		String className = certificateCacheModel.className;

		if ((className != null) && (className.length() == 0)) {
			certificateCacheModel.className = null;
		}

		certificateCacheModel.classPK = getClassPK();

		certificateCacheModel.name = getName();

		String name = certificateCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			certificateCacheModel.name = null;
		}

		certificateCacheModel.certificateType = getCertificateType();

		String certificateType = certificateCacheModel.certificateType;

		if ((certificateType != null) && (certificateType.length() == 0)) {
			certificateCacheModel.certificateType = null;
		}

		certificateCacheModel.universityId = getUniversityId();

		certificateCacheModel.graduationYear = getGraduationYear();

		certificateCacheModel.grade = getGrade();

		String grade = certificateCacheModel.grade;

		if ((grade != null) && (grade.length() == 0)) {
			certificateCacheModel.grade = null;
		}

		certificateCacheModel.groupId = getGroupId();

		certificateCacheModel.companyId = getCompanyId();

		certificateCacheModel.userId = getUserId();

		certificateCacheModel.userName = getUserName();

		String userName = certificateCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			certificateCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			certificateCacheModel.createDate = createDate.getTime();
		}
		else {
			certificateCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			certificateCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			certificateCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		Date courseTimeFrom = getCourseTimeFrom();

		if (courseTimeFrom != null) {
			certificateCacheModel.courseTimeFrom = courseTimeFrom.getTime();
		}
		else {
			certificateCacheModel.courseTimeFrom = Long.MIN_VALUE;
		}

		Date courseTimeTo = getCourseTimeTo();

		if (courseTimeTo != null) {
			certificateCacheModel.courseTimeTo = courseTimeTo.getTime();
		}
		else {
			certificateCacheModel.courseTimeTo = Long.MIN_VALUE;
		}

		return certificateCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(33);

		sb.append("{certificateId=");
		sb.append(getCertificateId());
		sb.append(", className=");
		sb.append(getClassName());
		sb.append(", classPK=");
		sb.append(getClassPK());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", certificateType=");
		sb.append(getCertificateType());
		sb.append(", universityId=");
		sb.append(getUniversityId());
		sb.append(", graduationYear=");
		sb.append(getGraduationYear());
		sb.append(", grade=");
		sb.append(getGrade());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", courseTimeFrom=");
		sb.append(getCourseTimeFrom());
		sb.append(", courseTimeTo=");
		sb.append(getCourseTimeTo());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(52);

		sb.append("<model><model-name>");
		sb.append("vn.com.ecopharma.hrm.rc.model.Certificate");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>certificateId</column-name><column-value><![CDATA[");
		sb.append(getCertificateId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>className</column-name><column-value><![CDATA[");
		sb.append(getClassName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>classPK</column-name><column-value><![CDATA[");
		sb.append(getClassPK());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>certificateType</column-name><column-value><![CDATA[");
		sb.append(getCertificateType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>universityId</column-name><column-value><![CDATA[");
		sb.append(getUniversityId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>graduationYear</column-name><column-value><![CDATA[");
		sb.append(getGraduationYear());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>grade</column-name><column-value><![CDATA[");
		sb.append(getGrade());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>courseTimeFrom</column-name><column-value><![CDATA[");
		sb.append(getCourseTimeFrom());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>courseTimeTo</column-name><column-value><![CDATA[");
		sb.append(getCourseTimeTo());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Certificate.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			Certificate.class
		};
	private long _certificateId;
	private String _className;
	private String _originalClassName;
	private long _classPK;
	private long _originalClassPK;
	private boolean _setOriginalClassPK;
	private String _name;
	private String _certificateType;
	private long _universityId;
	private int _graduationYear;
	private String _grade;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private Date _courseTimeFrom;
	private Date _courseTimeTo;
	private long _columnBitmask;
	private Certificate _escapedModel;
}