/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.com.ecopharma.hrm.rc.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import vn.com.ecopharma.hrm.rc.model.EvaluationCriteriaKeyValue;
import vn.com.ecopharma.hrm.rc.model.EvaluationCriteriaKeyValueModel;
import vn.com.ecopharma.hrm.rc.model.EvaluationCriteriaKeyValueSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the EvaluationCriteriaKeyValue service. Represents a row in the &quot;eco_rcp_EvaluationCriteriaKeyValue&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.com.ecopharma.hrm.rc.model.EvaluationCriteriaKeyValueModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EvaluationCriteriaKeyValueImpl}.
 * </p>
 *
 * @author tvt
 * @see EvaluationCriteriaKeyValueImpl
 * @see vn.com.ecopharma.hrm.rc.model.EvaluationCriteriaKeyValue
 * @see vn.com.ecopharma.hrm.rc.model.EvaluationCriteriaKeyValueModel
 * @generated
 */
@JSON(strict = true)
public class EvaluationCriteriaKeyValueModelImpl extends BaseModelImpl<EvaluationCriteriaKeyValue>
	implements EvaluationCriteriaKeyValueModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a evaluation criteria key value model instance should use the {@link vn.com.ecopharma.hrm.rc.model.EvaluationCriteriaKeyValue} interface instead.
	 */
	public static final String TABLE_NAME = "eco_rcp_EvaluationCriteriaKeyValue";
	public static final Object[][] TABLE_COLUMNS = {
			{ "evaluationCriteriaKeyValueId", Types.BIGINT },
			{ "evaluationCriteriaId", Types.BIGINT },
			{ "key_", Types.VARCHAR },
			{ "value", Types.INTEGER },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table eco_rcp_EvaluationCriteriaKeyValue (evaluationCriteriaKeyValueId LONG not null primary key,evaluationCriteriaId LONG,key_ VARCHAR(75) null,value INTEGER,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table eco_rcp_EvaluationCriteriaKeyValue";
	public static final String ORDER_BY_JPQL = " ORDER BY evaluationCriteriaKeyValue.evaluationCriteriaKeyValueId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY eco_rcp_EvaluationCriteriaKeyValue.evaluationCriteriaKeyValueId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.com.ecopharma.hrm.rc.model.EvaluationCriteriaKeyValue"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.com.ecopharma.hrm.rc.model.EvaluationCriteriaKeyValue"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.vn.com.ecopharma.hrm.rc.model.EvaluationCriteriaKeyValue"),
			true);
	public static long EVALUATIONCRITERIAID_COLUMN_BITMASK = 1L;
	public static long KEY_COLUMN_BITMASK = 2L;
	public static long EVALUATIONCRITERIAKEYVALUEID_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static EvaluationCriteriaKeyValue toModel(
		EvaluationCriteriaKeyValueSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		EvaluationCriteriaKeyValue model = new EvaluationCriteriaKeyValueImpl();

		model.setEvaluationCriteriaKeyValueId(soapModel.getEvaluationCriteriaKeyValueId());
		model.setEvaluationCriteriaId(soapModel.getEvaluationCriteriaId());
		model.setKey(soapModel.getKey());
		model.setValue(soapModel.getValue());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<EvaluationCriteriaKeyValue> toModels(
		EvaluationCriteriaKeyValueSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<EvaluationCriteriaKeyValue> models = new ArrayList<EvaluationCriteriaKeyValue>(soapModels.length);

		for (EvaluationCriteriaKeyValueSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.com.ecopharma.hrm.rc.model.EvaluationCriteriaKeyValue"));

	public EvaluationCriteriaKeyValueModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _evaluationCriteriaKeyValueId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEvaluationCriteriaKeyValueId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _evaluationCriteriaKeyValueId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return EvaluationCriteriaKeyValue.class;
	}

	@Override
	public String getModelClassName() {
		return EvaluationCriteriaKeyValue.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("evaluationCriteriaKeyValueId",
			getEvaluationCriteriaKeyValueId());
		attributes.put("evaluationCriteriaId", getEvaluationCriteriaId());
		attributes.put("key", getKey());
		attributes.put("value", getValue());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long evaluationCriteriaKeyValueId = (Long)attributes.get(
				"evaluationCriteriaKeyValueId");

		if (evaluationCriteriaKeyValueId != null) {
			setEvaluationCriteriaKeyValueId(evaluationCriteriaKeyValueId);
		}

		Long evaluationCriteriaId = (Long)attributes.get("evaluationCriteriaId");

		if (evaluationCriteriaId != null) {
			setEvaluationCriteriaId(evaluationCriteriaId);
		}

		String key = (String)attributes.get("key");

		if (key != null) {
			setKey(key);
		}

		Integer value = (Integer)attributes.get("value");

		if (value != null) {
			setValue(value);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}
	}

	@JSON
	@Override
	public long getEvaluationCriteriaKeyValueId() {
		return _evaluationCriteriaKeyValueId;
	}

	@Override
	public void setEvaluationCriteriaKeyValueId(
		long evaluationCriteriaKeyValueId) {
		_evaluationCriteriaKeyValueId = evaluationCriteriaKeyValueId;
	}

	@JSON
	@Override
	public long getEvaluationCriteriaId() {
		return _evaluationCriteriaId;
	}

	@Override
	public void setEvaluationCriteriaId(long evaluationCriteriaId) {
		_columnBitmask |= EVALUATIONCRITERIAID_COLUMN_BITMASK;

		if (!_setOriginalEvaluationCriteriaId) {
			_setOriginalEvaluationCriteriaId = true;

			_originalEvaluationCriteriaId = _evaluationCriteriaId;
		}

		_evaluationCriteriaId = evaluationCriteriaId;
	}

	public long getOriginalEvaluationCriteriaId() {
		return _originalEvaluationCriteriaId;
	}

	@JSON
	@Override
	public String getKey() {
		if (_key == null) {
			return StringPool.BLANK;
		}
		else {
			return _key;
		}
	}

	@Override
	public void setKey(String key) {
		_columnBitmask |= KEY_COLUMN_BITMASK;

		if (_originalKey == null) {
			_originalKey = _key;
		}

		_key = key;
	}

	public String getOriginalKey() {
		return GetterUtil.getString(_originalKey);
	}

	@JSON
	@Override
	public int getValue() {
		return _value;
	}

	@Override
	public void setValue(int value) {
		_value = value;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			EvaluationCriteriaKeyValue.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public EvaluationCriteriaKeyValue toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (EvaluationCriteriaKeyValue)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EvaluationCriteriaKeyValueImpl evaluationCriteriaKeyValueImpl = new EvaluationCriteriaKeyValueImpl();

		evaluationCriteriaKeyValueImpl.setEvaluationCriteriaKeyValueId(getEvaluationCriteriaKeyValueId());
		evaluationCriteriaKeyValueImpl.setEvaluationCriteriaId(getEvaluationCriteriaId());
		evaluationCriteriaKeyValueImpl.setKey(getKey());
		evaluationCriteriaKeyValueImpl.setValue(getValue());
		evaluationCriteriaKeyValueImpl.setGroupId(getGroupId());
		evaluationCriteriaKeyValueImpl.setCompanyId(getCompanyId());
		evaluationCriteriaKeyValueImpl.setUserId(getUserId());
		evaluationCriteriaKeyValueImpl.setUserName(getUserName());
		evaluationCriteriaKeyValueImpl.setCreateDate(getCreateDate());
		evaluationCriteriaKeyValueImpl.setModifiedDate(getModifiedDate());

		evaluationCriteriaKeyValueImpl.resetOriginalValues();

		return evaluationCriteriaKeyValueImpl;
	}

	@Override
	public int compareTo(EvaluationCriteriaKeyValue evaluationCriteriaKeyValue) {
		long primaryKey = evaluationCriteriaKeyValue.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof EvaluationCriteriaKeyValue)) {
			return false;
		}

		EvaluationCriteriaKeyValue evaluationCriteriaKeyValue = (EvaluationCriteriaKeyValue)obj;

		long primaryKey = evaluationCriteriaKeyValue.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		EvaluationCriteriaKeyValueModelImpl evaluationCriteriaKeyValueModelImpl = this;

		evaluationCriteriaKeyValueModelImpl._originalEvaluationCriteriaId = evaluationCriteriaKeyValueModelImpl._evaluationCriteriaId;

		evaluationCriteriaKeyValueModelImpl._setOriginalEvaluationCriteriaId = false;

		evaluationCriteriaKeyValueModelImpl._originalKey = evaluationCriteriaKeyValueModelImpl._key;

		evaluationCriteriaKeyValueModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<EvaluationCriteriaKeyValue> toCacheModel() {
		EvaluationCriteriaKeyValueCacheModel evaluationCriteriaKeyValueCacheModel =
			new EvaluationCriteriaKeyValueCacheModel();

		evaluationCriteriaKeyValueCacheModel.evaluationCriteriaKeyValueId = getEvaluationCriteriaKeyValueId();

		evaluationCriteriaKeyValueCacheModel.evaluationCriteriaId = getEvaluationCriteriaId();

		evaluationCriteriaKeyValueCacheModel.key = getKey();

		String key = evaluationCriteriaKeyValueCacheModel.key;

		if ((key != null) && (key.length() == 0)) {
			evaluationCriteriaKeyValueCacheModel.key = null;
		}

		evaluationCriteriaKeyValueCacheModel.value = getValue();

		evaluationCriteriaKeyValueCacheModel.groupId = getGroupId();

		evaluationCriteriaKeyValueCacheModel.companyId = getCompanyId();

		evaluationCriteriaKeyValueCacheModel.userId = getUserId();

		evaluationCriteriaKeyValueCacheModel.userName = getUserName();

		String userName = evaluationCriteriaKeyValueCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			evaluationCriteriaKeyValueCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			evaluationCriteriaKeyValueCacheModel.createDate = createDate.getTime();
		}
		else {
			evaluationCriteriaKeyValueCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			evaluationCriteriaKeyValueCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			evaluationCriteriaKeyValueCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return evaluationCriteriaKeyValueCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(21);

		sb.append("{evaluationCriteriaKeyValueId=");
		sb.append(getEvaluationCriteriaKeyValueId());
		sb.append(", evaluationCriteriaId=");
		sb.append(getEvaluationCriteriaId());
		sb.append(", key=");
		sb.append(getKey());
		sb.append(", value=");
		sb.append(getValue());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(34);

		sb.append("<model><model-name>");
		sb.append("vn.com.ecopharma.hrm.rc.model.EvaluationCriteriaKeyValue");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>evaluationCriteriaKeyValueId</column-name><column-value><![CDATA[");
		sb.append(getEvaluationCriteriaKeyValueId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>evaluationCriteriaId</column-name><column-value><![CDATA[");
		sb.append(getEvaluationCriteriaId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>key</column-name><column-value><![CDATA[");
		sb.append(getKey());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>value</column-name><column-value><![CDATA[");
		sb.append(getValue());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = EvaluationCriteriaKeyValue.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			EvaluationCriteriaKeyValue.class
		};
	private long _evaluationCriteriaKeyValueId;
	private long _evaluationCriteriaId;
	private long _originalEvaluationCriteriaId;
	private boolean _setOriginalEvaluationCriteriaId;
	private String _key;
	private String _originalKey;
	private int _value;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private long _columnBitmask;
	private EvaluationCriteriaKeyValue _escapedModel;
}