/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.com.ecopharma.hrm.rc.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import vn.com.ecopharma.hrm.rc.model.VacancyCandidate;
import vn.com.ecopharma.hrm.rc.model.VacancyCandidateModel;
import vn.com.ecopharma.hrm.rc.model.VacancyCandidateSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the VacancyCandidate service. Represents a row in the &quot;eco_rcp_VacancyCandidate&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.com.ecopharma.hrm.rc.model.VacancyCandidateModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VacancyCandidateImpl}.
 * </p>
 *
 * @author tvt
 * @see VacancyCandidateImpl
 * @see vn.com.ecopharma.hrm.rc.model.VacancyCandidate
 * @see vn.com.ecopharma.hrm.rc.model.VacancyCandidateModel
 * @generated
 */
@JSON(strict = true)
public class VacancyCandidateModelImpl extends BaseModelImpl<VacancyCandidate>
	implements VacancyCandidateModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a vacancy candidate model instance should use the {@link vn.com.ecopharma.hrm.rc.model.VacancyCandidate} interface instead.
	 */
	public static final String TABLE_NAME = "eco_rcp_VacancyCandidate";
	public static final Object[][] TABLE_COLUMNS = {
			{ "vacancyCandidateId", Types.BIGINT },
			{ "vacancyId", Types.BIGINT },
			{ "candidateId", Types.BIGINT },
			{ "status", Types.INTEGER },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "type_", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table eco_rcp_VacancyCandidate (vacancyCandidateId LONG not null primary key,vacancyId LONG,candidateId LONG,status INTEGER,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,type_ VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table eco_rcp_VacancyCandidate";
	public static final String ORDER_BY_JPQL = " ORDER BY vacancyCandidate.vacancyCandidateId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY eco_rcp_VacancyCandidate.vacancyCandidateId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.com.ecopharma.hrm.rc.model.VacancyCandidate"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.com.ecopharma.hrm.rc.model.VacancyCandidate"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.vn.com.ecopharma.hrm.rc.model.VacancyCandidate"),
			true);
	public static long CANDIDATEID_COLUMN_BITMASK = 1L;
	public static long STATUS_COLUMN_BITMASK = 2L;
	public static long TYPE_COLUMN_BITMASK = 4L;
	public static long VACANCYID_COLUMN_BITMASK = 8L;
	public static long VACANCYCANDIDATEID_COLUMN_BITMASK = 16L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static VacancyCandidate toModel(VacancyCandidateSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		VacancyCandidate model = new VacancyCandidateImpl();

		model.setVacancyCandidateId(soapModel.getVacancyCandidateId());
		model.setVacancyId(soapModel.getVacancyId());
		model.setCandidateId(soapModel.getCandidateId());
		model.setStatus(soapModel.getStatus());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setType(soapModel.getType());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<VacancyCandidate> toModels(
		VacancyCandidateSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<VacancyCandidate> models = new ArrayList<VacancyCandidate>(soapModels.length);

		for (VacancyCandidateSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.com.ecopharma.hrm.rc.model.VacancyCandidate"));

	public VacancyCandidateModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _vacancyCandidateId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setVacancyCandidateId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _vacancyCandidateId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return VacancyCandidate.class;
	}

	@Override
	public String getModelClassName() {
		return VacancyCandidate.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("vacancyCandidateId", getVacancyCandidateId());
		attributes.put("vacancyId", getVacancyId());
		attributes.put("candidateId", getCandidateId());
		attributes.put("status", getStatus());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("type", getType());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long vacancyCandidateId = (Long)attributes.get("vacancyCandidateId");

		if (vacancyCandidateId != null) {
			setVacancyCandidateId(vacancyCandidateId);
		}

		Long vacancyId = (Long)attributes.get("vacancyId");

		if (vacancyId != null) {
			setVacancyId(vacancyId);
		}

		Long candidateId = (Long)attributes.get("candidateId");

		if (candidateId != null) {
			setCandidateId(candidateId);
		}

		Integer status = (Integer)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String type = (String)attributes.get("type");

		if (type != null) {
			setType(type);
		}
	}

	@JSON
	@Override
	public long getVacancyCandidateId() {
		return _vacancyCandidateId;
	}

	@Override
	public void setVacancyCandidateId(long vacancyCandidateId) {
		_vacancyCandidateId = vacancyCandidateId;
	}

	@JSON
	@Override
	public long getVacancyId() {
		return _vacancyId;
	}

	@Override
	public void setVacancyId(long vacancyId) {
		_columnBitmask |= VACANCYID_COLUMN_BITMASK;

		if (!_setOriginalVacancyId) {
			_setOriginalVacancyId = true;

			_originalVacancyId = _vacancyId;
		}

		_vacancyId = vacancyId;
	}

	public long getOriginalVacancyId() {
		return _originalVacancyId;
	}

	@JSON
	@Override
	public long getCandidateId() {
		return _candidateId;
	}

	@Override
	public void setCandidateId(long candidateId) {
		_columnBitmask |= CANDIDATEID_COLUMN_BITMASK;

		if (!_setOriginalCandidateId) {
			_setOriginalCandidateId = true;

			_originalCandidateId = _candidateId;
		}

		_candidateId = candidateId;
	}

	public long getOriginalCandidateId() {
		return _originalCandidateId;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_columnBitmask |= STATUS_COLUMN_BITMASK;

		if (!_setOriginalStatus) {
			_setOriginalStatus = true;

			_originalStatus = _status;
		}

		_status = status;
	}

	public int getOriginalStatus() {
		return _originalStatus;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getType() {
		if (_type == null) {
			return StringPool.BLANK;
		}
		else {
			return _type;
		}
	}

	@Override
	public void setType(String type) {
		_columnBitmask |= TYPE_COLUMN_BITMASK;

		if (_originalType == null) {
			_originalType = _type;
		}

		_type = type;
	}

	public String getOriginalType() {
		return GetterUtil.getString(_originalType);
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			VacancyCandidate.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public VacancyCandidate toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (VacancyCandidate)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		VacancyCandidateImpl vacancyCandidateImpl = new VacancyCandidateImpl();

		vacancyCandidateImpl.setVacancyCandidateId(getVacancyCandidateId());
		vacancyCandidateImpl.setVacancyId(getVacancyId());
		vacancyCandidateImpl.setCandidateId(getCandidateId());
		vacancyCandidateImpl.setStatus(getStatus());
		vacancyCandidateImpl.setGroupId(getGroupId());
		vacancyCandidateImpl.setCompanyId(getCompanyId());
		vacancyCandidateImpl.setUserId(getUserId());
		vacancyCandidateImpl.setUserName(getUserName());
		vacancyCandidateImpl.setCreateDate(getCreateDate());
		vacancyCandidateImpl.setModifiedDate(getModifiedDate());
		vacancyCandidateImpl.setType(getType());

		vacancyCandidateImpl.resetOriginalValues();

		return vacancyCandidateImpl;
	}

	@Override
	public int compareTo(VacancyCandidate vacancyCandidate) {
		long primaryKey = vacancyCandidate.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof VacancyCandidate)) {
			return false;
		}

		VacancyCandidate vacancyCandidate = (VacancyCandidate)obj;

		long primaryKey = vacancyCandidate.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		VacancyCandidateModelImpl vacancyCandidateModelImpl = this;

		vacancyCandidateModelImpl._originalVacancyId = vacancyCandidateModelImpl._vacancyId;

		vacancyCandidateModelImpl._setOriginalVacancyId = false;

		vacancyCandidateModelImpl._originalCandidateId = vacancyCandidateModelImpl._candidateId;

		vacancyCandidateModelImpl._setOriginalCandidateId = false;

		vacancyCandidateModelImpl._originalStatus = vacancyCandidateModelImpl._status;

		vacancyCandidateModelImpl._setOriginalStatus = false;

		vacancyCandidateModelImpl._originalType = vacancyCandidateModelImpl._type;

		vacancyCandidateModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<VacancyCandidate> toCacheModel() {
		VacancyCandidateCacheModel vacancyCandidateCacheModel = new VacancyCandidateCacheModel();

		vacancyCandidateCacheModel.vacancyCandidateId = getVacancyCandidateId();

		vacancyCandidateCacheModel.vacancyId = getVacancyId();

		vacancyCandidateCacheModel.candidateId = getCandidateId();

		vacancyCandidateCacheModel.status = getStatus();

		vacancyCandidateCacheModel.groupId = getGroupId();

		vacancyCandidateCacheModel.companyId = getCompanyId();

		vacancyCandidateCacheModel.userId = getUserId();

		vacancyCandidateCacheModel.userName = getUserName();

		String userName = vacancyCandidateCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			vacancyCandidateCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			vacancyCandidateCacheModel.createDate = createDate.getTime();
		}
		else {
			vacancyCandidateCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			vacancyCandidateCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			vacancyCandidateCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		vacancyCandidateCacheModel.type = getType();

		String type = vacancyCandidateCacheModel.type;

		if ((type != null) && (type.length() == 0)) {
			vacancyCandidateCacheModel.type = null;
		}

		return vacancyCandidateCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(23);

		sb.append("{vacancyCandidateId=");
		sb.append(getVacancyCandidateId());
		sb.append(", vacancyId=");
		sb.append(getVacancyId());
		sb.append(", candidateId=");
		sb.append(getCandidateId());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", type=");
		sb.append(getType());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(37);

		sb.append("<model><model-name>");
		sb.append("vn.com.ecopharma.hrm.rc.model.VacancyCandidate");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>vacancyCandidateId</column-name><column-value><![CDATA[");
		sb.append(getVacancyCandidateId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>vacancyId</column-name><column-value><![CDATA[");
		sb.append(getVacancyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>candidateId</column-name><column-value><![CDATA[");
		sb.append(getCandidateId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>type</column-name><column-value><![CDATA[");
		sb.append(getType());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = VacancyCandidate.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			VacancyCandidate.class
		};
	private long _vacancyCandidateId;
	private long _vacancyId;
	private long _originalVacancyId;
	private boolean _setOriginalVacancyId;
	private long _candidateId;
	private long _originalCandidateId;
	private boolean _setOriginalCandidateId;
	private int _status;
	private int _originalStatus;
	private boolean _setOriginalStatus;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private String _type;
	private String _originalType;
	private long _columnBitmask;
	private VacancyCandidate _escapedModel;
}